/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './challenge';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../providers/task-data';
import * as import5 from '../../providers/storage';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import19 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/components/toolbar/toolbar';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import31 from 'ionic-angular/components/navbar/navbar';
import * as import32 from '@angular/common/src/directives/ng_for';
import * as import33 from 'ionic-angular/components/grid/grid';
import * as import34 from 'ionic-angular/components/content/content';
import * as import35 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import36 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import37 from 'ionic-angular/components/avatar/avatar';
import * as import38 from '@angular/common/src/directives/ng_if';
import * as import39 from '@angular/core/src/security';
import * as import40 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import41 from 'ionic-angular/components/button/button';
export class Wrapper_ChallengePage {
  context:import0.ChallengePage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.ChallengePage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ChallengePage_Host:import2.RenderComponentType = (null as any);
class _View_ChallengePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TaskData_0_4:import4.TaskData;
  _Storage_0_5:import5.Storage;
  _ChallengePage_0_6:Wrapper_ChallengePage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage_Host0,renderType_ChallengePage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-challenge',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ChallengePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TaskData_0_4 = new import4.TaskData(this.parentInjector.get(import10.Http));
    this._Storage_0_5 = new import5.Storage();
    this._ChallengePage_0_6 = new Wrapper_ChallengePage(this.parentInjector.get(import11.NavController),this._TaskData_0_4,this._Storage_0_5);
    this._appEl_0.initComponent(this._ChallengePage_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._ChallengePage_0_6.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.TaskData) && (0 === requestNodeIndex))) { return this._TaskData_0_4; }
    if (((token === import5.Storage) && (0 === requestNodeIndex))) { return this._Storage_0_5; }
    if (((token === import0.ChallengePage) && (0 === requestNodeIndex))) { return this._ChallengePage_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChallengePage_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ChallengePage_Host === (null as any))) { (renderType_ChallengePage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ChallengePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ChallengePageNgFactory:import13.ComponentFactory<import0.ChallengePage> = new import13.ComponentFactory<import0.ChallengePage>('page-challenge',viewFactory_ChallengePage_Host0,import0.ChallengePage);
const styles_ChallengePage:any[] = ([] as any[]);
var renderType_ChallengePage:import2.RenderComponentType = (null as any);
class _View_ChallengePage0 extends import1.AppView<import0.ChallengePage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import14.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import15.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import16.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import17.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _Grid_12_3:import18.Wrapper_Grid;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import19.Wrapper_NgFor;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage0,renderType_ChallengePage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import14.Wrapper_Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import22.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','font-size: 18px;');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'我的挑战',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import17.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import17.Wrapper_Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','no-padding contentGray');
    this.renderer.setElementAttribute(this._el_12,'style','width: 100%; height: 100%;');
    this._Grid_12_3 = new import18.Wrapper_Grid();
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'style','height: 1px; background-color: #FFFFFF;');
    this._text_15 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._appEl_16 = new import3.AppElement(16,12,this,this._anchor_16);
    this._TemplateRef_16_5 = new import28.TemplateRef_(this._appEl_16,viewFactory_ChallengePage1);
    this._NgFor_16_6 = new import19.Wrapper_NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_18
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import31.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import24.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import28.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import32.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    if (((token === import33.Grid) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Grid_12_3.context; }
    if (((token === import34.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._Grid_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_4:any = this.context.tasks;
    this._NgFor_16_6.check_ngForOf(currVal_4,throwOnChange,false);
    this._NgFor_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_ChallengePage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ChallengePage> {
  if ((renderType_ChallengePage === (null as any))) { (renderType_ChallengePage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_ChallengePage,{})); }
  return new _View_ChallengePage0(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import18.Wrapper_Row;
  _text_3:any;
  _el_4:any;
  _Col_4_3:import18.Wrapper_Col;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _Col_9_3:import18.Wrapper_Col;
  _text_10:any;
  _el_11:any;
  _Row_11_3:import18.Wrapper_Row;
  _text_12:any;
  _el_13:any;
  _Col_13_3:import18.Wrapper_Col;
  _text_14:any;
  _el_15:any;
  _Avatar_15_3:import35.Wrapper_Avatar;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _Col_21_3:import18.Wrapper_Col;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import18.Wrapper_Col;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _Row_29_3:import18.Wrapper_Row;
  _text_30:any;
  _el_31:any;
  _Col_31_3:import18.Wrapper_Col;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _Row_35_3:import18.Wrapper_Row;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _Col_38_3:import18.Wrapper_Col;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _Col_43_3:import18.Wrapper_Col;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _Col_46_3:import18.Wrapper_Col;
  _text_47:any;
  _anchor_48:any;
  /*private*/ _appEl_48:import3.AppElement;
  _TemplateRef_48_5:any;
  _NgIf_48_6:import36.Wrapper_NgIf;
  _text_49:any;
  _anchor_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _TemplateRef_50_5:any;
  _NgIf_50_6:import36.Wrapper_NgIf;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _Col_53_3:import18.Wrapper_Col;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _Col_56_3:import18.Wrapper_Col;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _Col_59_3:import18.Wrapper_Col;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _Col_62_3:import18.Wrapper_Col;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import3.AppElement;
  _TemplateRef_64_5:any;
  _NgIf_64_6:import36.Wrapper_NgIf;
  _text_65:any;
  _anchor_66:any;
  /*private*/ _appEl_66:import3.AppElement;
  _TemplateRef_66_5:any;
  _NgIf_66_6:import36.Wrapper_NgIf;
  _text_67:any;
  _anchor_68:any;
  /*private*/ _appEl_68:import3.AppElement;
  _TemplateRef_68_5:any;
  _NgIf_68_6:import36.Wrapper_NgIf;
  _text_69:any;
  _anchor_70:any;
  /*private*/ _appEl_70:import3.AppElement;
  _TemplateRef_70_5:any;
  _NgIf_70_6:import36.Wrapper_NgIf;
  _text_71:any;
  _anchor_72:any;
  /*private*/ _appEl_72:import3.AppElement;
  _TemplateRef_72_5:any;
  _NgIf_72_6:import36.Wrapper_NgIf;
  _text_73:any;
  _anchor_74:any;
  /*private*/ _appEl_74:import3.AppElement;
  _TemplateRef_74_5:any;
  _NgIf_74_6:import36.Wrapper_NgIf;
  _text_75:any;
  _anchor_76:any;
  /*private*/ _appEl_76:import3.AppElement;
  _TemplateRef_76_5:any;
  _NgIf_76_6:import36.Wrapper_NgIf;
  _text_77:any;
  _anchor_78:any;
  /*private*/ _appEl_78:import3.AppElement;
  _TemplateRef_78_5:any;
  _NgIf_78_6:import36.Wrapper_NgIf;
  _text_79:any;
  _anchor_80:any;
  /*private*/ _appEl_80:import3.AppElement;
  _TemplateRef_80_5:any;
  _NgIf_80_6:import36.Wrapper_NgIf;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage1,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','task-card');
    this.renderer.setElementAttribute(this._el_0,'style','height:101px;');
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','no-padding');
    this.renderer.setElementAttribute(this._el_2,'style','background-color:#fff; width: 100%; height: 100px;');
    this._Row_2_3 = new import18.Wrapper_Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','no-padding');
    this.renderer.setElementAttribute(this._el_4,'style','background-color: #FFFFFF; height: 100px; font-size:28px; color: #FFFFFF; text-align:center; line-height: 100px;');
    this.renderer.setElementAttribute(this._el_4,'width-33','');
    this._Col_4_3 = new import18.Wrapper_Col();
    this._text_5 = this.renderer.createText(this._el_4,'\n              ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'src','assets/img/preview.png');
    this.renderer.setElementAttribute(this._el_6,'style','width:100%; height:100%; background-color: #BBB');
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','padding-left');
    this.renderer.setElementAttribute(this._el_9,'style','height: 100px;');
    this.renderer.setElementAttribute(this._el_9,'width-67','');
    this._Col_9_3 = new import18.Wrapper_Col();
    this._text_10 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_11,'center','');
    this.renderer.setElementAttribute(this._el_11,'class','no-padding');
    this.renderer.setElementAttribute(this._el_11,'style','height: 25%;');
    this._Row_11_3 = new import18.Wrapper_Row();
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_13,'style','padding: 3px 3px 3px 3px;');
    this.renderer.setElementAttribute(this._el_13,'width-10','');
    this._Col_13_3 = new import18.Wrapper_Col();
    this._text_14 = this.renderer.createText(this._el_13,'\n                  ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-avatar',(null as any));
    this._Avatar_15_3 = new import35.Wrapper_Avatar();
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'img',(null as any));
    this.renderer.setElementAttribute(this._el_17,'style','border-radius: 25px;');
    this._text_18 = this.renderer.createText(this._el_15,'\n                  ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','no-padding');
    this.renderer.setElementAttribute(this._el_21,'style','font-size:9px; color: #4A4A4A;');
    this.renderer.setElementAttribute(this._el_21,'width-40','');
    this._Col_21_3 = new import18.Wrapper_Col();
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_11,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'style','font-size:9px; color: #4A4A4A;');
    this.renderer.setElementAttribute(this._el_24,'width-50','');
    this._Col_24_3 = new import18.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n                  ',(null as any));
    this._text_26 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_11,'\n              ',(null as any));
    this._text_28 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_9,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_29,'style','height: 50%;');
    this._Row_29_3 = new import18.Wrapper_Row();
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_31,'style','font-size: 14px;');
    this.renderer.setElementAttribute(this._el_31,'width-100','');
    this._Col_31_3 = new import18.Wrapper_Col();
    this._text_32 = this.renderer.createText(this._el_31,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n              ',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_9,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_35,'center','');
    this.renderer.setElementAttribute(this._el_35,'class','no-padding');
    this.renderer.setElementAttribute(this._el_35,'style','height: 20px;');
    this._Row_35_3 = new import18.Wrapper_Row();
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_37 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_38,'width-10','');
    this._Col_38_3 = new import18.Wrapper_Col();
    this._text_39 = this.renderer.createText(this._el_38,'\n                  ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'img',(null as any));
    this.renderer.setElementAttribute(this._el_40,'src','assets/img/money.svg');
    this._text_41 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','no-padding');
    this.renderer.setElementAttribute(this._el_43,'style','font-size: 12px;');
    this.renderer.setElementAttribute(this._el_43,'width-10','');
    this._Col_43_3 = new import18.Wrapper_Col();
    this._text_44 = this.renderer.createText(this._el_43,'',(null as any));
    this._text_45 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_46,'width-10','');
    this._Col_46_3 = new import18.Wrapper_Col();
    this._text_47 = this.renderer.createText(this._el_46,'\n                  ',(null as any));
    this._anchor_48 = this.renderer.createTemplateAnchor(this._el_46,(null as any));
    this._appEl_48 = new import3.AppElement(48,46,this,this._anchor_48);
    this._TemplateRef_48_5 = new import28.TemplateRef_(this._appEl_48,viewFactory_ChallengePage2);
    this._NgIf_48_6 = new import36.Wrapper_NgIf(this._appEl_48.vcRef,this._TemplateRef_48_5);
    this._text_49 = this.renderer.createText(this._el_46,'\n                  ',(null as any));
    this._anchor_50 = this.renderer.createTemplateAnchor(this._el_46,(null as any));
    this._appEl_50 = new import3.AppElement(50,46,this,this._anchor_50);
    this._TemplateRef_50_5 = new import28.TemplateRef_(this._appEl_50,viewFactory_ChallengePage3);
    this._NgIf_50_6 = new import36.Wrapper_NgIf(this._appEl_50.vcRef,this._TemplateRef_50_5);
    this._text_51 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._text_52 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','no-padding');
    this.renderer.setElementAttribute(this._el_53,'style','font-size: 12px;');
    this.renderer.setElementAttribute(this._el_53,'width-10','');
    this._Col_53_3 = new import18.Wrapper_Col();
    this._text_54 = this.renderer.createText(this._el_53,'',(null as any));
    this._text_55 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_56,'width-20','');
    this._Col_56_3 = new import18.Wrapper_Col();
    this._text_57 = this.renderer.createText(this._el_56,'\n                ',(null as any));
    this._text_58 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','no-padding');
    this.renderer.setElementAttribute(this._el_59,'style','font-size: 12px;');
    this.renderer.setElementAttribute(this._el_59,'width-10','');
    this._Col_59_3 = new import18.Wrapper_Col();
    this._text_60 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._text_61 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_35,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','no-padding');
    this.renderer.setElementAttribute(this._el_62,'width-20','');
    this._Col_62_3 = new import18.Wrapper_Col();
    this._text_63 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_64 = new import3.AppElement(64,62,this,this._anchor_64);
    this._TemplateRef_64_5 = new import28.TemplateRef_(this._appEl_64,viewFactory_ChallengePage4);
    this._NgIf_64_6 = new import36.Wrapper_NgIf(this._appEl_64.vcRef,this._TemplateRef_64_5);
    this._text_65 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_66 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_66 = new import3.AppElement(66,62,this,this._anchor_66);
    this._TemplateRef_66_5 = new import28.TemplateRef_(this._appEl_66,viewFactory_ChallengePage5);
    this._NgIf_66_6 = new import36.Wrapper_NgIf(this._appEl_66.vcRef,this._TemplateRef_66_5);
    this._text_67 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_68 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_68 = new import3.AppElement(68,62,this,this._anchor_68);
    this._TemplateRef_68_5 = new import28.TemplateRef_(this._appEl_68,viewFactory_ChallengePage6);
    this._NgIf_68_6 = new import36.Wrapper_NgIf(this._appEl_68.vcRef,this._TemplateRef_68_5);
    this._text_69 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_70 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_70 = new import3.AppElement(70,62,this,this._anchor_70);
    this._TemplateRef_70_5 = new import28.TemplateRef_(this._appEl_70,viewFactory_ChallengePage7);
    this._NgIf_70_6 = new import36.Wrapper_NgIf(this._appEl_70.vcRef,this._TemplateRef_70_5);
    this._text_71 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_72 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_72 = new import3.AppElement(72,62,this,this._anchor_72);
    this._TemplateRef_72_5 = new import28.TemplateRef_(this._appEl_72,viewFactory_ChallengePage8);
    this._NgIf_72_6 = new import36.Wrapper_NgIf(this._appEl_72.vcRef,this._TemplateRef_72_5);
    this._text_73 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_74 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_74 = new import3.AppElement(74,62,this,this._anchor_74);
    this._TemplateRef_74_5 = new import28.TemplateRef_(this._appEl_74,viewFactory_ChallengePage9);
    this._NgIf_74_6 = new import36.Wrapper_NgIf(this._appEl_74.vcRef,this._TemplateRef_74_5);
    this._text_75 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_76 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_76 = new import3.AppElement(76,62,this,this._anchor_76);
    this._TemplateRef_76_5 = new import28.TemplateRef_(this._appEl_76,viewFactory_ChallengePage10);
    this._NgIf_76_6 = new import36.Wrapper_NgIf(this._appEl_76.vcRef,this._TemplateRef_76_5);
    this._text_77 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_78 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_78 = new import3.AppElement(78,62,this,this._anchor_78);
    this._TemplateRef_78_5 = new import28.TemplateRef_(this._appEl_78,viewFactory_ChallengePage11);
    this._NgIf_78_6 = new import36.Wrapper_NgIf(this._appEl_78.vcRef,this._TemplateRef_78_5);
    this._text_79 = this.renderer.createText(this._el_62,'\n                  ',(null as any));
    this._anchor_80 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_80 = new import3.AppElement(80,62,this,this._anchor_80);
    this._TemplateRef_80_5 = new import28.TemplateRef_(this._appEl_80,viewFactory_ChallengePage12);
    this._NgIf_80_6 = new import36.Wrapper_NgIf(this._appEl_80.vcRef,this._TemplateRef_80_5);
    this._text_81 = this.renderer.createText(this._el_62,'\n                ',(null as any));
    this._text_82 = this.renderer.createText(this._el_35,'\n              ',(null as any));
    this._text_83 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_84 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_85 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_86,'style','height: 1px; background-color: #F5F5F5;');
    this._text_87 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this._expr_7 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._anchor_48,
      this._text_49,
      this._anchor_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._anchor_66,
      this._text_67,
      this._anchor_68,
      this._text_69,
      this._anchor_70,
      this._text_71,
      this._anchor_72,
      this._text_73,
      this._anchor_74,
      this._text_75,
      this._anchor_76,
      this._text_77,
      this._anchor_78,
      this._text_79,
      this._anchor_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Col) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Col_4_3.context; }
    if (((token === import37.Avatar) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Avatar_15_3.context; }
    if (((token === import33.Col) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Col_13_3.context; }
    if (((token === import33.Col) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Col_21_3.context; }
    if (((token === import33.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Col_24_3.context; }
    if (((token === import33.Row) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Row_11_3.context; }
    if (((token === import33.Col) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Col_31_3.context; }
    if (((token === import33.Row) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Row_29_3.context; }
    if (((token === import33.Col) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Col_38_3.context; }
    if (((token === import33.Col) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Col_43_3.context; }
    if (((token === import28.TemplateRef) && (48 === requestNodeIndex))) { return this._TemplateRef_48_5; }
    if (((token === import38.NgIf) && (48 === requestNodeIndex))) { return this._NgIf_48_6.context; }
    if (((token === import28.TemplateRef) && (50 === requestNodeIndex))) { return this._TemplateRef_50_5; }
    if (((token === import38.NgIf) && (50 === requestNodeIndex))) { return this._NgIf_50_6.context; }
    if (((token === import33.Col) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Col_46_3.context; }
    if (((token === import33.Col) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Col_53_3.context; }
    if (((token === import33.Col) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Col_56_3.context; }
    if (((token === import33.Col) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Col_59_3.context; }
    if (((token === import28.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import38.NgIf) && (64 === requestNodeIndex))) { return this._NgIf_64_6.context; }
    if (((token === import28.TemplateRef) && (66 === requestNodeIndex))) { return this._TemplateRef_66_5; }
    if (((token === import38.NgIf) && (66 === requestNodeIndex))) { return this._NgIf_66_6.context; }
    if (((token === import28.TemplateRef) && (68 === requestNodeIndex))) { return this._TemplateRef_68_5; }
    if (((token === import38.NgIf) && (68 === requestNodeIndex))) { return this._NgIf_68_6.context; }
    if (((token === import28.TemplateRef) && (70 === requestNodeIndex))) { return this._TemplateRef_70_5; }
    if (((token === import38.NgIf) && (70 === requestNodeIndex))) { return this._NgIf_70_6.context; }
    if (((token === import28.TemplateRef) && (72 === requestNodeIndex))) { return this._TemplateRef_72_5; }
    if (((token === import38.NgIf) && (72 === requestNodeIndex))) { return this._NgIf_72_6.context; }
    if (((token === import28.TemplateRef) && (74 === requestNodeIndex))) { return this._TemplateRef_74_5; }
    if (((token === import38.NgIf) && (74 === requestNodeIndex))) { return this._NgIf_74_6.context; }
    if (((token === import28.TemplateRef) && (76 === requestNodeIndex))) { return this._TemplateRef_76_5; }
    if (((token === import38.NgIf) && (76 === requestNodeIndex))) { return this._NgIf_76_6.context; }
    if (((token === import28.TemplateRef) && (78 === requestNodeIndex))) { return this._TemplateRef_78_5; }
    if (((token === import38.NgIf) && (78 === requestNodeIndex))) { return this._NgIf_78_6.context; }
    if (((token === import28.TemplateRef) && (80 === requestNodeIndex))) { return this._TemplateRef_80_5; }
    if (((token === import38.NgIf) && (80 === requestNodeIndex))) { return this._NgIf_80_6.context; }
    if (((token === import33.Col) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Col_62_3.context; }
    if (((token === import33.Row) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Row_35_3.context; }
    if (((token === import33.Col) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._Col_9_3.context; }
    if (((token === import33.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._Row_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Row_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Col_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Col_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    this._Row_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Col_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Avatar_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Col_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Row_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    this._Col_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Row_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    this._Col_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    this._Col_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    this._Col_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_5:any = this.context.$implicit.hasFavor;
    this._NgIf_48_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_48_6.detectChangesInternal(this,this._anchor_48,throwOnChange);
    const currVal_6:boolean = !this.context.$implicit.hasFavor;
    this._NgIf_50_6.check_ngIf(currVal_6,throwOnChange,false);
    this._NgIf_50_6.detectChangesInternal(this,this._anchor_50,throwOnChange);
    this._Col_53_3.detectChangesInternal(this,this._el_53,throwOnChange);
    this._Col_56_3.detectChangesInternal(this,this._el_56,throwOnChange);
    this._Col_59_3.detectChangesInternal(this,this._el_59,throwOnChange);
    this._Col_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    const currVal_8:any = (this.context.$implicit.taskTypeNumber == 0);
    this._NgIf_64_6.check_ngIf(currVal_8,throwOnChange,false);
    this._NgIf_64_6.detectChangesInternal(this,this._anchor_64,throwOnChange);
    const currVal_9:any = (this.context.$implicit.taskTypeNumber == 1);
    this._NgIf_66_6.check_ngIf(currVal_9,throwOnChange,false);
    this._NgIf_66_6.detectChangesInternal(this,this._anchor_66,throwOnChange);
    const currVal_10:any = (this.context.$implicit.taskTypeNumber == 2);
    this._NgIf_68_6.check_ngIf(currVal_10,throwOnChange,false);
    this._NgIf_68_6.detectChangesInternal(this,this._anchor_68,throwOnChange);
    const currVal_11:any = (this.context.$implicit.taskTypeNumber == 31);
    this._NgIf_70_6.check_ngIf(currVal_11,throwOnChange,false);
    this._NgIf_70_6.detectChangesInternal(this,this._anchor_70,throwOnChange);
    const currVal_12:any = (this.context.$implicit.taskTypeNumber == 32);
    this._NgIf_72_6.check_ngIf(currVal_12,throwOnChange,false);
    this._NgIf_72_6.detectChangesInternal(this,this._anchor_72,throwOnChange);
    const currVal_13:any = (this.context.$implicit.taskTypeNumber == 33);
    this._NgIf_74_6.check_ngIf(currVal_13,throwOnChange,false);
    this._NgIf_74_6.detectChangesInternal(this,this._anchor_74,throwOnChange);
    const currVal_14:any = (this.context.$implicit.taskTypeNumber == 41);
    this._NgIf_76_6.check_ngIf(currVal_14,throwOnChange,false);
    this._NgIf_76_6.detectChangesInternal(this,this._anchor_76,throwOnChange);
    const currVal_15:any = (this.context.$implicit.taskTypeNumber == 42);
    this._NgIf_78_6.check_ngIf(currVal_15,throwOnChange,false);
    this._NgIf_78_6.detectChangesInternal(this,this._anchor_78,throwOnChange);
    const currVal_16:any = (this.context.$implicit.taskTypeNumber == 5);
    this._NgIf_80_6.check_ngIf(currVal_16,throwOnChange,false);
    this._NgIf_80_6.detectChangesInternal(this,this._anchor_80,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.taskRecipient.image,'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_17,'src',this.viewUtils.sanitizer.sanitize(import39.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(2,'\n                  ',this.context.$implicit.taskRecipient.name,'|',this.context.$implicit.taskRecipient.title,'\n                ');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_22,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'\n                  ',this.context.$implicit.taskDescription,'\n                ');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_32,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(1,'\n                  ',this.context.$implicit.moneyNum,'\n                ');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_44,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = import6.interpolate(1,'\n                  ',this.context.$implicit.favorNum,'\n                ');
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_54,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onTaskClick(this.context.$implicit,this.context.$implicit.state)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ChallengePage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage1(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage2,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','assets/img/heart_red.svg');
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ChallengePage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage2(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage3,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','assets/img/heart.svg');
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ChallengePage3(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage3(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage4,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','blue');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #ffffff;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'正在直播',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'blue';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage4(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage4(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage5,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','blue');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #ffffff;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'等在直播',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'blue';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage5(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage5(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage6,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','blue');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #ffffff;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'领取任务',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'blue';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage6(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage6(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage7,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','blue');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #ffffff;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'点击评价',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'blue';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage7(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage7(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage8,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','gray');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #000000;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'已经评价',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'gray';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage8(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage8(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage9 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage9,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','gray');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #000000;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'查看评价',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'gray';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage9(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage9(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage10 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage10,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','gray');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #000000;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'任务成功',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'gray';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage10(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage10(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage11 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage11,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','gray');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #000000;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'任务失败',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'gray';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage11(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage11(viewUtils,parentInjector,declarationEl);
}
class _View_ChallengePage12 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import40.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_ChallengePage12,renderType_ChallengePage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','gray');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'style','width:62px; height:22px; font-size: 9px; color: #000000;');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import40.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'任务过期',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'gray';
    this._Button_0_4.check_color(currVal_0,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChallengePage12(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ChallengePage12(viewUtils,parentInjector,declarationEl);
}