/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../providers/login';
import * as import5 from '../../providers/storage';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/navigation/nav-params';
import * as import13 from '@angular/forms/src/form_builder';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import25 from '@angular/core/src/linker/query_list';
import * as import26 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import28 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import30 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import32 from 'ionic-angular/config/config';
import * as import33 from '@angular/core/src/linker/element_ref';
import * as import34 from 'ionic-angular/navigation/view-controller';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from 'ionic-angular/components/toolbar/toolbar';
import * as import37 from 'ionic-angular/util/keyboard';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from 'ionic-angular/components/tabs/tabs';
import * as import40 from 'ionic-angular/gestures/gesture-controller';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from 'ionic-angular/components/item/item-reorder';
import * as import43 from 'ionic-angular/platform/platform';
import * as import44 from '@angular/core/src/linker/template_ref';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import46 from 'ionic-angular/components/navbar/navbar';
import * as import47 from 'ionic-angular/components/label/label';
import * as import48 from '@angular/forms/src/directives/validators';
import * as import49 from '@angular/forms/src/validators';
import * as import50 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import51 from '@angular/forms/src/directives/ng_control';
import * as import52 from '@angular/forms/src/directives/ng_control_status';
import * as import53 from 'ionic-angular/components/input/input';
import * as import54 from 'ionic-angular/components/item/item';
import * as import55 from 'ionic-angular/components/list/list';
import * as import56 from '@angular/common/src/directives/ng_if';
import * as import57 from 'ionic-angular/components/button/button';
import * as import58 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import59 from '@angular/forms/src/directives/control_container';
import * as import60 from 'ionic-angular/components/grid/grid';
import * as import61 from 'ionic-angular/components/content/content';
import * as import62 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import63 from 'ionic-angular/components/typography/typography';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Login_0_4:import4.Login;
  _Storage_0_5:import5.Storage;
  _LoginPage_0_6:Wrapper_LoginPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Login_0_4 = new import4.Login(this.parentInjector.get(import10.Http));
    this._Storage_0_5 = new import5.Storage();
    this._LoginPage_0_6 = new Wrapper_LoginPage(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.NavParams),this.parentInjector.get(import13.FormBuilder),this._Login_0_4,this._Storage_0_5);
    this._appEl_0.initComponent(this._LoginPage_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_6.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.Login) && (0 === requestNodeIndex))) { return this._Login_0_4; }
    if (((token === import5.Storage) && (0 === requestNodeIndex))) { return this._Storage_0_5; }
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import15.ComponentFactory<import0.LoginPage> = new import15.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import16.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import17.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import18.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import19.Wrapper_Content;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _Grid_13_3:import20.Wrapper_Grid;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _Row_17_3:import20.Wrapper_Row;
  _text_18:any;
  _el_19:any;
  _FormGroupDirective_19_3:import21.Wrapper_FormGroupDirective;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import22.Wrapper_NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _List_21_3:import23.Wrapper_List;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import24.Wrapper_Item;
  _ItemContent_23_5:import24.Wrapper_ItemContent;
  _query_Label_23_0:import25.QueryList<any>;
  _query_Button_23_1:import25.QueryList<any>;
  _query_Icon_23_2:import25.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Label_25_3:import26.Wrapper_Label;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _RequiredValidator_28_4:import27.Wrapper_RequiredValidator;
  _NG_VALIDATORS_28_5:any[];
  _FormControlName_28_6:import28.Wrapper_FormControlName;
  _NgControl_28_7:any;
  _NgControlStatus_28_8:import22.Wrapper_NgControlStatus;
  _TextInput_28_9:import29.Wrapper_TextInput;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Item_34_4:import24.Wrapper_Item;
  _ItemContent_34_5:import24.Wrapper_ItemContent;
  _query_Label_34_0:import25.QueryList<any>;
  _query_Button_34_1:import25.QueryList<any>;
  _query_Icon_34_2:import25.QueryList<any>;
  _text_35:any;
  _el_36:any;
  _Label_36_3:import26.Wrapper_Label;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _RequiredValidator_39_4:import27.Wrapper_RequiredValidator;
  _NG_VALIDATORS_39_5:any[];
  _FormControlName_39_6:import28.Wrapper_FormControlName;
  _NgControl_39_7:any;
  _NgControlStatus_39_8:import22.Wrapper_NgControlStatus;
  _TextInput_39_9:import29.Wrapper_TextInput;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _TemplateRef_45_5:any;
  _NgIf_45_6:import30.Wrapper_NgIf;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _TemplateRef_47_5:any;
  _NgIf_47_6:import30.Wrapper_NgIf;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _Button_49_4:import31.Wrapper_Button;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_38:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import16.Wrapper_Header(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import34.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import17.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import17.Wrapper_Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import34.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','font-size: 18px;');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import36.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'账户登录',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import19.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import19.Wrapper_Content(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import37.Keyboard),this.parentInjector.get(import38.NgZone),this.parentInjector.get(import34.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','contentGray');
    this.renderer.setElementAttribute(this._el_13,'padding','');
    this.renderer.setElementAttribute(this._el_13,'style','height: 150%; width: 100%');
    this._Grid_13_3 = new import20.Wrapper_Grid();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'style','height: 150px; background-color: #F5F5F5;');
    this._text_16 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_17,'center','');
    this.renderer.setElementAttribute(this._el_17,'class','no-padding');
    this.renderer.setElementAttribute(this._el_17,'style','width: 100%');
    this._Row_17_3 = new import20.Wrapper_Row();
    this._text_18 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'form',(null as any));
    this.renderer.setElementAttribute(this._el_19,'style','width: 100%; background-color: #F5F5F5;');
    this._FormGroupDirective_19_3 = new import21.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_19_4 = this._FormGroupDirective_19_3.context;
    this._NgControlStatusGroup_19_5 = new import22.Wrapper_NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','no-padding');
    this.renderer.setElementAttribute(this._el_21,'no-lines','');
    this.renderer.setElementAttribute(this._el_21,'style','width: 100%; background-color: #F5F5F5;');
    this._List_21_3 = new import23.Wrapper_List(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import40.GestureController));
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this.renderer.setElementAttribute(this._el_23,'style','background-color: #F5F5F5;');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import24.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import24.Wrapper_Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import42.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import24.Wrapper_ItemContent();
    this._query_Label_23_0 = new import25.QueryList<any>();
    this._query_Button_23_1 = new import25.QueryList<any>();
    this._query_Icon_23_2 = new import25.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_25,'floating','');
    this._Label_25_3 = new import26.Wrapper_Label(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_25),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'学号',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'clearInput','');
    this.renderer.setElementAttribute(this._el_28,'formControlName','LoginId');
    this.renderer.setElementAttribute(this._el_28,'required','');
    this.renderer.setElementAttribute(this._el_28,'type','number');
    this._appEl_28 = new import3.AppElement(28,23,this,this._el_28);
    var compView_28:any = import29.viewFactory_TextInput0(this.viewUtils,this.injector(28),this._appEl_28);
    this._RequiredValidator_28_4 = new import27.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_28_5 = [this._RequiredValidator_28_4.context];
    this._FormControlName_28_6 = new import28.Wrapper_FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_28_5,(null as any),(null as any));
    this._NgControl_28_7 = this._FormControlName_28_6.context;
    this._NgControlStatus_28_8 = new import22.Wrapper_NgControlStatus(this._NgControl_28_7);
    this._TextInput_28_9 = new import29.Wrapper_TextInput(this.parentInjector.get(import32.Config),this.parentInjector.get(import41.Form),this._Item_23_4.context,this.parentInjector.get(import35.App),this.parentInjector.get(import43.Platform),new import33.ElementRef(this._el_28),this.renderer,this._Content_10_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_28_7);
    this._appEl_28.initComponent(this._TextInput_28_9.context,([] as any[]),compView_28);
    compView_28.create(this._TextInput_28_9.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_23_0.reset([this._Label_25_3.context]);
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_25]),
      ([] as any[]).concat([
        this._text_24,
        this._text_27,
        this._text_29,
        this._text_30
      ]
      ),
      ([] as any[]).concat([this._el_28]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'style','height: 1px; background-color: #9B9B9B;');
    this._text_33 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','item item-block');
    this.renderer.setElementAttribute(this._el_34,'style','background-color: #F5F5F5;');
    this._appEl_34 = new import3.AppElement(34,21,this,this._el_34);
    var compView_34:any = import24.viewFactory_Item0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Item_34_4 = new import24.Wrapper_Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import42.ItemReorder,(null as any)));
    this._ItemContent_34_5 = new import24.Wrapper_ItemContent();
    this._query_Label_34_0 = new import25.QueryList<any>();
    this._query_Button_34_1 = new import25.QueryList<any>();
    this._query_Icon_34_2 = new import25.QueryList<any>();
    this._appEl_34.initComponent(this._Item_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_36,'floating','');
    this._Label_36_3 = new import26.Wrapper_Label(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_36),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'密码',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_39,'clearInput','');
    this.renderer.setElementAttribute(this._el_39,'formControlName','LoginPwd');
    this.renderer.setElementAttribute(this._el_39,'required','');
    this.renderer.setElementAttribute(this._el_39,'type','password');
    this._appEl_39 = new import3.AppElement(39,34,this,this._el_39);
    var compView_39:any = import29.viewFactory_TextInput0(this.viewUtils,this.injector(39),this._appEl_39);
    this._RequiredValidator_39_4 = new import27.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_39_5 = [this._RequiredValidator_39_4.context];
    this._FormControlName_39_6 = new import28.Wrapper_FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_39_5,(null as any),(null as any));
    this._NgControl_39_7 = this._FormControlName_39_6.context;
    this._NgControlStatus_39_8 = new import22.Wrapper_NgControlStatus(this._NgControl_39_7);
    this._TextInput_39_9 = new import29.Wrapper_TextInput(this.parentInjector.get(import32.Config),this.parentInjector.get(import41.Form),this._Item_34_4.context,this.parentInjector.get(import35.App),this.parentInjector.get(import43.Platform),new import33.ElementRef(this._el_39),this.renderer,this._Content_10_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_39_7);
    this._appEl_39.initComponent(this._TextInput_39_9.context,([] as any[]),compView_39);
    compView_39.create(this._TextInput_39_9.context,([] as any[]),(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_34_0.reset([this._Label_36_3.context]);
    this._Item_34_4.context.contentLabel = this._query_Label_34_0.first;
    compView_34.create(this._Item_34_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_36]),
      ([] as any[]).concat([
        this._text_35,
        this._text_38,
        this._text_40
      ]
      ),
      ([] as any[]).concat([this._el_39]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'style','height: 1px; background-color: #9B9B9B;');
    this._text_43 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._anchor_45 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_45 = new import3.AppElement(45,19,this,this._anchor_45);
    this._TemplateRef_45_5 = new import44.TemplateRef_(this._appEl_45,viewFactory_LoginPage1);
    this._NgIf_45_6 = new import30.Wrapper_NgIf(this._appEl_45.vcRef,this._TemplateRef_45_5);
    this._text_46 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_47 = new import3.AppElement(47,19,this,this._anchor_47);
    this._TemplateRef_47_5 = new import44.TemplateRef_(this._appEl_47,viewFactory_LoginPage2);
    this._NgIf_47_6 = new import30.Wrapper_NgIf(this._appEl_47.vcRef,this._TemplateRef_47_5);
    this._text_48 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_49,'block','');
    this.renderer.setElementAttribute(this._el_49,'color','blue');
    this.renderer.setElementAttribute(this._el_49,'ion-button','');
    this.renderer.setElementAttribute(this._el_49,'type','submit');
    this._appEl_49 = new import3.AppElement(49,19,this,this._el_49);
    var compView_49:any = import31.viewFactory_Button0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Button_49_4 = new import31.Wrapper_Button((null as any),'',this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_49),this.renderer);
    this._appEl_49.initComponent(this._Button_49_4.context,([] as any[]),compView_49);
    this._text_50 = this.renderer.createText((null as any),'登录',(null as any));
    compView_49.create(this._Button_49_4.context,[([] as any[]).concat([this._text_50])],(null as any));
    this._text_51 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._text_52 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._text_53 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._text_54 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._text_12,
        this._el_13,
        this._text_55,
        this._text_56
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'submit',this.eventHandler(this._handle_submit_19_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_19,'reset',this.eventHandler(this._handle_reset_19_1.bind(this)));
    this._expr_7 = import9.UNINITIALIZED;
    this._expr_8 = import9.UNINITIALIZED;
    this._expr_9 = import9.UNINITIALIZED;
    this._expr_10 = import9.UNINITIALIZED;
    this._expr_11 = import9.UNINITIALIZED;
    this._expr_12 = import9.UNINITIALIZED;
    this._expr_14 = import9.UNINITIALIZED;
    this._expr_16 = import9.UNINITIALIZED;
    this._expr_17 = import9.UNINITIALIZED;
    this._expr_18 = import9.UNINITIALIZED;
    this._expr_19 = import9.UNINITIALIZED;
    this._expr_20 = import9.UNINITIALIZED;
    this._expr_21 = import9.UNINITIALIZED;
    this._expr_25 = import9.UNINITIALIZED;
    this._expr_27 = import9.UNINITIALIZED;
    this._expr_28 = import9.UNINITIALIZED;
    this._expr_29 = import9.UNINITIALIZED;
    this._expr_30 = import9.UNINITIALIZED;
    this._expr_31 = import9.UNINITIALIZED;
    this._expr_32 = import9.UNINITIALIZED;
    this._expr_38 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_49,'click',this.eventHandler(this._handle_click_49_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import46.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import36.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import47.Label) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Label_25_3.context; }
    if (((token === import48.RequiredValidator) && (28 === requestNodeIndex))) { return this._RequiredValidator_28_4.context; }
    if (((token === import49.NG_VALIDATORS) && (28 === requestNodeIndex))) { return this._NG_VALIDATORS_28_5; }
    if (((token === import50.FormControlName) && (28 === requestNodeIndex))) { return this._FormControlName_28_6.context; }
    if (((token === import51.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_7; }
    if (((token === import52.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_8.context; }
    if (((token === import53.TextInput) && (28 === requestNodeIndex))) { return this._TextInput_28_9.context; }
    if (((token === import54.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_23_4.context; }
    if (((token === import54.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_23_5.context; }
    if (((token === import47.Label) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Label_36_3.context; }
    if (((token === import48.RequiredValidator) && (39 === requestNodeIndex))) { return this._RequiredValidator_39_4.context; }
    if (((token === import49.NG_VALIDATORS) && (39 === requestNodeIndex))) { return this._NG_VALIDATORS_39_5; }
    if (((token === import50.FormControlName) && (39 === requestNodeIndex))) { return this._FormControlName_39_6.context; }
    if (((token === import51.NgControl) && (39 === requestNodeIndex))) { return this._NgControl_39_7; }
    if (((token === import52.NgControlStatus) && (39 === requestNodeIndex))) { return this._NgControlStatus_39_8.context; }
    if (((token === import53.TextInput) && (39 === requestNodeIndex))) { return this._TextInput_39_9.context; }
    if (((token === import54.Item) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_34_4.context; }
    if (((token === import54.ItemContent) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_34_5.context; }
    if (((token === import55.List) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._List_21_3.context; }
    if (((token === import44.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import56.NgIf) && (45 === requestNodeIndex))) { return this._NgIf_45_6.context; }
    if (((token === import44.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import56.NgIf) && (47 === requestNodeIndex))) { return this._NgIf_47_6.context; }
    if (((token === import57.Button) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Button_49_4.context; }
    if (((token === import58.FormGroupDirective) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._FormGroupDirective_19_3.context; }
    if (((token === import59.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ControlContainer_19_4; }
    if (((token === import52.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControlStatusGroup_19_5.context; }
    if (((token === import60.Row) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Row_17_3.context; }
    if (((token === import60.Grid) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Grid_13_3.context; }
    if (((token === import61.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._Grid_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Row_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    const currVal_6:any = this.context.loginForm;
    this._FormGroupDirective_19_3.check_form(currVal_6,throwOnChange,false);
    this._FormGroupDirective_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatusGroup_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    this._List_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Label_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_13:any = '';
    this._RequiredValidator_28_4.check_required(currVal_13,throwOnChange,false);
    this._RequiredValidator_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_15:any = 'LoginId';
    this._FormControlName_28_6.check_name(currVal_15,throwOnChange,false);
    this._FormControlName_28_6.detectChangesInternal(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_8.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_22:any = '';
    this._TextInput_28_9.check_clearInput(currVal_22,throwOnChange,false);
    const currVal_23:any = 'number';
    this._TextInput_28_9.check_type(currVal_23,throwOnChange,false);
    this._TextInput_28_9.detectChangesInternal(this,this._el_28,throwOnChange);
    if (this._Item_34_4.detectChangesInternal(this,this._el_34,throwOnChange)) { this._appEl_34.componentView.markAsCheckOnce(); }
    this._ItemContent_34_5.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Label_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_24:any = '';
    this._RequiredValidator_39_4.check_required(currVal_24,throwOnChange,false);
    this._RequiredValidator_39_4.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_26:any = 'LoginPwd';
    this._FormControlName_39_6.check_name(currVal_26,throwOnChange,false);
    this._FormControlName_39_6.detectChangesInternal(this,this._el_39,throwOnChange);
    this._NgControlStatus_39_8.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_33:any = '';
    this._TextInput_39_9.check_clearInput(currVal_33,throwOnChange,false);
    const currVal_34:any = 'password';
    this._TextInput_39_9.check_type(currVal_34,throwOnChange,false);
    this._TextInput_39_9.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_35:any = this.context.succeed;
    this._NgIf_45_6.check_ngIf(currVal_35,throwOnChange,false);
    this._NgIf_45_6.detectChangesInternal(this,this._anchor_45,throwOnChange);
    const currVal_36:boolean = !this.context.succeed;
    this._NgIf_47_6.check_ngIf(currVal_36,throwOnChange,false);
    this._NgIf_47_6.detectChangesInternal(this,this._anchor_47,throwOnChange);
    const currVal_39:any = '';
    this._Button_49_4.check_block(currVal_39,throwOnChange,false);
    const currVal_40:any = 'blue';
    this._Button_49_4.check_color(currVal_40,throwOnChange,false);
    if (this._Button_49_4.detectChangesInternal(this,this._el_49,throwOnChange)) { this._appEl_49.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_34_1.dirty) {
        this._query_Button_34_1.reset(([] as any[]));
        this._Item_34_4.context._buttons = this._query_Button_34_1;
        this._query_Button_34_1.notifyOnChanges();
      }
      if (this._query_Icon_34_2.dirty) {
        this._query_Icon_34_2.reset(([] as any[]));
        this._Item_34_4.context._icons = this._query_Icon_34_2;
        this._query_Icon_34_2.notifyOnChanges();
      }
      this._TextInput_28_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      this._TextInput_39_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_34_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_49_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._NgControlStatusGroup_19_5.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_19_5.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_19_5.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_19_5.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_19_5.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_19_5.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = (this._RequiredValidator_28_4.context.required? '': (null as any));
    if (import6.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementAttribute(this._el_28,'required',((currVal_14 == (null as any))? (null as any): currVal_14.toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_16:any = this._NgControlStatus_28_8.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_28,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_28_8.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_28,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_28_8.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_28,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_28_8.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_28,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_28_8.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_28,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_28_8.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_28,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_25:any = (this._RequiredValidator_39_4.context.required? '': (null as any));
    if (import6.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementAttribute(this._el_39,'required',((currVal_25 == (null as any))? (null as any): currVal_25.toString()));
      this._expr_25 = currVal_25;
    }
    const currVal_27:any = this._NgControlStatus_39_8.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_39,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_39_8.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_39,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_39_8.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_39,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_39_8.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_39,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_39_8.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_39,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_39_8.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_39,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_38:boolean = !this.context.loginForm.valid;
    if (import6.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementProperty(this._el_49,'disabled',currVal_38);
      this._expr_38 = currVal_38;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_28_6.context.ngOnDestroy();
    this._TextInput_28_9.context.ngOnDestroy();
    this._FormControlName_39_6.context.ngOnDestroy();
    this._TextInput_39_9.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_submit_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_19_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_19_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_19_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login(this.context.loginForm.value,$event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage1 extends import1.AppView<any> {
  _el_0:any;
  _Typography_0_3:import62.Wrapper_Typography;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage1,renderType_LoginPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','danger');
    this.renderer.setElementAttribute(this._el_0,'style','font-size:12px; text-align: center;');
    this._Typography_0_3 = new import62.Wrapper_Typography(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'账号或密码错误',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import63.Typography) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Typography_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'danger';
    this._Typography_0_3.check_color(currVal_0,throwOnChange,false);
    this._Typography_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage1(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage2 extends import1.AppView<any> {
  _el_0:any;
  _Typography_0_3:import62.Wrapper_Typography;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage2,renderType_LoginPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','dark');
    this.renderer.setElementAttribute(this._el_0,'style','font-size:12px; text-align: center;');
    this._Typography_0_3 = new import62.Wrapper_Typography(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'请输入清华Info账号名与密码',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import63.Typography) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Typography_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'dark';
    this._Typography_0_3.check_color(currVal_0,throwOnChange,false);
    this._Typography_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage2(viewUtils,parentInjector,declarationEl);
}