/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './rulebooks';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from 'ionic-angular/components/app/app';
import * as import19 from 'ionic-angular/components/toolbar/toolbar';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from 'ionic-angular/components/tabs/tabs';
import * as import23 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import24 from 'ionic-angular/components/navbar/navbar';
import * as import25 from 'ionic-angular/components/content/content';
export class Wrapper_RulebooksPage {
  context:import0.RulebooksPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.RulebooksPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RulebooksPage_Host:import2.RenderComponentType = (null as any);
class _View_RulebooksPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RulebooksPage_0_4:Wrapper_RulebooksPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RulebooksPage_Host0,renderType_RulebooksPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-rulebooks',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RulebooksPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RulebooksPage_0_4 = new Wrapper_RulebooksPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._RulebooksPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RulebooksPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RulebooksPage) && (0 === requestNodeIndex))) { return this._RulebooksPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RulebooksPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RulebooksPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RulebooksPage_Host === (null as any))) { (renderType_RulebooksPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RulebooksPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RulebooksPageNgFactory:import10.ComponentFactory<import0.RulebooksPage> = new import10.ComponentFactory<import0.RulebooksPage>('page-rulebooks',viewFactory_RulebooksPage_Host0,import0.RulebooksPage);
const styles_RulebooksPage:any[] = ([] as any[]);
var renderType_RulebooksPage:import2.RenderComponentType = (null as any);
class _View_RulebooksPage0 extends import1.AppView<import0.RulebooksPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import13.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import14.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RulebooksPage0,renderType_RulebooksPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import18.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','font-size: 18px;');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import19.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'规则说明',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','contentGray');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import14.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Wrapper_Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import18.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import22.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n      系统目前处于内部测试阶段，在使用过程中，您发布任务与接收任务使用的是虚拟金币，而根据直播的质量您将获得额外的积分。具体规则如下。\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'br',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n      1.金币流通规则\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n      （1）初次登陆系统，您会获得1000虚拟金币，在为期一个月的测试过程中，如果您有额外的金币需求，请联系我们，我们将免费为您充值。但是请您将1000金币想象成真实的货币，在充值前三思。：）\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n      （2）发布任务将耗费您的金币，最少支付1个金币，最多则没有上限，您可以通过增加金币的数量，吸引他人领取您的任务。\n    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n      （3）当其他人发布任务时，如果您也希望观看直播并支持，您可以使用金币 “支持” 他人发布的任务，您支出的金币会用于增加该任务的奖励金币。\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n      （4）当您接收他人发出的任务，并顺利完成后，您将获得所有初始金币（任务发起者的金币）和支持金币（其他支持者的金币）。\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n      （5）当您接收他人发出的任务，并在约定时间开始任务，但任务中断或失败，您将不能获得金币，他人支出的金币将原路径退回。\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_12,'br',(null as any));
    this._text_38 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n      2.积分流通规则\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n      （1）初次登陆系统，所有用户的积分为0，所有人白手起家。\n    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n      （2）每次直播的开始都将刺激系统产生积分，并且分配给任务发起者，任务完成者，以及支持者。\n    ',(null as any));
    this._text_47 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n      （3）每次直播产生的积分数由观看该任务直播的人数以及点赞的数量所决定。最终产生的积分为定额，若任务完成，积分则以2:2:6的比例分配给任务发布者、任务支持者和任务完成者。\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n      （4）当您接收他人发出的任务，并在约定时间开始任务，但任务中断或失败，您将不能获得积分。系统产生的积分以5:5的比例分配给任务发布者和任务支持者。\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n      （5）当您接收他人发出的任务，但没有在约定时间内开始进行任务。系统将按照一定比例扣除您的积分。第一次违约扣除您积分总数的1%向上取整，第二次扣除2%向上取整，以此增加。当违约次数达到10次，您的账户将被冻结。\n    ',(null as any));
    this._text_56 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_12,'p',(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n      （6）本次内部测试持续时间为1个月，最终积分数的前十名将获得团队给予的奖金，最高奖金额为2000元。\n    ',(null as any));
    this._text_59 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_60
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import24.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import19.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import25.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_RulebooksPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RulebooksPage> {
  if ((renderType_RulebooksPage === (null as any))) { (renderType_RulebooksPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_RulebooksPage,{})); }
  return new _View_RulebooksPage0(viewUtils,parentInjector,declarationEl);
}