/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './help';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from 'ionic-angular/components/app/app';
import * as import23 from 'ionic-angular/components/toolbar/toolbar';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/components/tabs/tabs';
import * as import27 from 'ionic-angular/gestures/gesture-controller';
import * as import28 from 'ionic-angular/util/form';
import * as import29 from 'ionic-angular/components/item/item-reorder';
import * as import30 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import31 from 'ionic-angular/components/navbar/navbar';
import * as import32 from 'ionic-angular/components/item/item';
import * as import33 from 'ionic-angular/components/list/list';
import * as import34 from 'ionic-angular/components/slides/slides';
import * as import35 from 'ionic-angular/components/content/content';
export class Wrapper_HelpPage {
  context:import0.HelpPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.HelpPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_HelpPage_Host:import2.RenderComponentType = (null as any);
class _View_HelpPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HelpPage_0_4:Wrapper_HelpPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HelpPage_Host0,renderType_HelpPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-help',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HelpPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HelpPage_0_4 = new Wrapper_HelpPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._HelpPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HelpPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HelpPage) && (0 === requestNodeIndex))) { return this._HelpPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HelpPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HelpPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HelpPage_Host === (null as any))) { (renderType_HelpPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HelpPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HelpPageNgFactory:import10.ComponentFactory<import0.HelpPage> = new import10.ComponentFactory<import0.HelpPage>('page-help',viewFactory_HelpPage_Host0,import0.HelpPage);
const styles_HelpPage:any[] = ([] as any[]);
var renderType_HelpPage:import2.RenderComponentType = (null as any);
class _View_HelpPage0 extends import1.AppView<import0.HelpPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import13.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import14.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _Slides_12_4:import15.Wrapper_Slides;
  _text_13:any;
  _el_14:any;
  _List_14_3:import16.Wrapper_List;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import17.Wrapper_Item;
  _ItemContent_18_5:import17.Wrapper_ItemContent;
  _query_Label_18_0:import18.QueryList<any>;
  _query_Button_18_1:import18.QueryList<any>;
  _query_Icon_18_2:import18.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import17.Wrapper_Item;
  _ItemContent_23_5:import17.Wrapper_ItemContent;
  _query_Label_23_0:import18.QueryList<any>;
  _query_Button_23_1:import18.QueryList<any>;
  _query_Icon_23_2:import18.QueryList<any>;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Item_28_4:import17.Wrapper_Item;
  _ItemContent_28_5:import17.Wrapper_ItemContent;
  _query_Label_28_0:import18.QueryList<any>;
  _query_Button_28_1:import18.QueryList<any>;
  _query_Icon_28_2:import18.QueryList<any>;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HelpPage0,renderType_HelpPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import22.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','font-size: 18px;');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import23.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'帮助',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import14.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Wrapper_Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import22.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import26.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-slides',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','contentGray');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import15.viewFactory_Slides0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Slides_12_4 = new import15.Wrapper_Slides(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Slides_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_14,'no-lines','');
    this.renderer.setElementAttribute(this._el_14,'style','width: 100%;');
    this._List_14_3 = new import16.Wrapper_List(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import27.GestureController));
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'style','height: 8px; background-color: #F5F5F5;');
    this._text_17 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','paddingItem item item-block');
    this.renderer.setElementAttribute(this._el_18,'datail-push','');
    this.renderer.setElementAttribute(this._el_18,'ion-item','');
    this._appEl_18 = new import3.AppElement(18,14,this,this._el_18);
    var compView_18:any = import17.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import17.Wrapper_Item(this.parentInjector.get(import28.Form),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import29.ItemReorder,(null as any)));
    this._ItemContent_18_5 = new import17.Wrapper_ItemContent();
    this._query_Label_18_0 = new import18.QueryList<any>();
    this._query_Button_18_1 = new import18.QueryList<any>();
    this._query_Icon_18_2 = new import18.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'用户协议',(null as any));
    this._query_Label_18_0.reset(([] as any[]));
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_19]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'style','height: 2px; background-color: #F5F5F5;');
    this._text_22 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','paddingItem item item-block');
    this.renderer.setElementAttribute(this._el_23,'datail-push','');
    this.renderer.setElementAttribute(this._el_23,'ion-item','');
    this._appEl_23 = new import3.AppElement(23,14,this,this._el_23);
    var compView_23:any = import17.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import17.Wrapper_Item(this.parentInjector.get(import28.Form),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import29.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import17.Wrapper_ItemContent();
    this._query_Label_23_0 = new import18.QueryList<any>();
    this._query_Button_23_1 = new import18.QueryList<any>();
    this._query_Icon_23_2 = new import18.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'使用手册',(null as any));
    this._query_Label_23_0.reset(([] as any[]));
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_24]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'style','height: 2px; background-color: #F5F5F5;');
    this._text_27 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','paddingItem item item-block');
    this.renderer.setElementAttribute(this._el_28,'datail-push','');
    this.renderer.setElementAttribute(this._el_28,'ion-item','');
    this._appEl_28 = new import3.AppElement(28,14,this,this._el_28);
    var compView_28:any = import17.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import17.Wrapper_Item(this.parentInjector.get(import28.Form),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import29.ItemReorder,(null as any)));
    this._ItemContent_28_5 = new import17.Wrapper_ItemContent();
    this._query_Label_28_0 = new import18.QueryList<any>();
    this._query_Button_28_1 = new import18.QueryList<any>();
    this._query_Icon_28_2 = new import18.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'反馈与举报',(null as any));
    this._query_Label_28_0.reset(([] as any[]));
    this._Item_28_4.context.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_29]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_12.create(this._Slides_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_32
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import31.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import23.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import32.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_18_4.context; }
    if (((token === import32.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_18_5.context; }
    if (((token === import32.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Item_23_4.context; }
    if (((token === import32.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ItemContent_23_5.context; }
    if (((token === import32.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_28_4.context; }
    if (((token === import32.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_28_5.context; }
    if (((token === import33.List) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._List_14_3.context; }
    if (((token === import34.Slides) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Slides_12_4.context; }
    if (((token === import35.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    if (this._Slides_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._List_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    if (this._Item_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    this._ItemContent_28_5.detectChangesInternal(this,this._el_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset(([] as any[]));
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset(([] as any[]));
        this._Item_28_4.context._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset(([] as any[]));
        this._Item_28_4.context._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.itemTapped(this.context.agreement)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.itemTapped(this.context.manual)) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.itemTapped(this.context.report)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HelpPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HelpPage> {
  if ((renderType_HelpPage === (null as any))) { (renderType_HelpPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_HelpPage,{})); }
  return new _View_HelpPage0(viewUtils,parentInjector,declarationEl);
}