/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './add-task';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../providers/task-data';
import * as import5 from '../../providers/storage';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/navigation/nav-params';
import * as import13 from 'ionic-angular/components/alert/alert';
import * as import14 from 'ionic-angular/components/loading/loading';
import * as import15 from '@angular/forms/src/form_builder';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from 'ionic-angular/components/app/app';
import * as import35 from 'ionic-angular/components/toolbar/toolbar';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from 'ionic-angular/util/form';
import * as import40 from 'ionic-angular/components/item/item';
import * as import41 from 'ionic-angular/platform/platform';
import * as import42 from 'ionic-angular/components/item/item-reorder';
import * as import43 from 'ionic-angular/components/picker/picker';
import * as import44 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import45 from 'ionic-angular/components/button/button';
import * as import46 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import47 from 'ionic-angular/components/navbar/navbar';
import * as import48 from 'ionic-angular/components/grid/grid';
import * as import49 from '@angular/forms/src/directives/ng_model';
import * as import50 from '@angular/forms/src/directives/ng_control';
import * as import51 from '@angular/forms/src/directives/ng_control_status';
import * as import52 from 'ionic-angular/components/input/input';
import * as import53 from 'ionic-angular/components/datetime/datetime';
import * as import54 from '@angular/forms/src/directives/control_value_accessor';
import * as import55 from 'ionic-angular/components/content/content';
export class Wrapper_AddTaskPage {
  context:import0.AddTaskPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.AddTaskPage(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AddTaskPage_Host:import2.RenderComponentType = (null as any);
class _View_AddTaskPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TaskData_0_4:import4.TaskData;
  _Storage_0_5:import5.Storage;
  _AddTaskPage_0_6:Wrapper_AddTaskPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AddTaskPage_Host0,renderType_AddTaskPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-add-task',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AddTaskPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TaskData_0_4 = new import4.TaskData(this.parentInjector.get(import10.Http));
    this._Storage_0_5 = new import5.Storage();
    this._AddTaskPage_0_6 = new Wrapper_AddTaskPage(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.NavParams),this.parentInjector.get(import13.AlertController),this.parentInjector.get(import14.LoadingController),this._TaskData_0_4,this._Storage_0_5,this.parentInjector.get(import15.FormBuilder));
    this._appEl_0.initComponent(this._AddTaskPage_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._AddTaskPage_0_6.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.TaskData) && (0 === requestNodeIndex))) { return this._TaskData_0_4; }
    if (((token === import5.Storage) && (0 === requestNodeIndex))) { return this._Storage_0_5; }
    if (((token === import0.AddTaskPage) && (0 === requestNodeIndex))) { return this._AddTaskPage_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AddTaskPage_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AddTaskPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AddTaskPage_Host === (null as any))) { (renderType_AddTaskPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AddTaskPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AddTaskPageNgFactory:import17.ComponentFactory<import0.AddTaskPage> = new import17.ComponentFactory<import0.AddTaskPage>('page-add-task',viewFactory_AddTaskPage_Host0,import0.AddTaskPage);
const styles_AddTaskPage:any[] = ([] as any[]);
var renderType_AddTaskPage:import2.RenderComponentType = (null as any);
class _View_AddTaskPage0 extends import1.AppView<import0.AddTaskPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import18.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import19.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import20.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _ToolbarItem_8_3:import21.Wrapper_ToolbarItem;
  _query_Button_8_0:import22.QueryList<any>;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Button_10_4:import23.Wrapper_Button;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Content_18_4:import24.Wrapper_Content;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Grid_22_3:import25.Wrapper_Grid;
  _text_23:any;
  _el_24:any;
  _Row_24_3:import25.Wrapper_Row;
  _text_25:any;
  _el_26:any;
  _Col_26_3:import25.Wrapper_Col;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _Col_29_3:import25.Wrapper_Col;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _Row_33_3:import25.Wrapper_Row;
  _text_34:any;
  _el_35:any;
  _Col_35_3:import25.Wrapper_Col;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _NgModel_37_4:import26.Wrapper_NgModel;
  _NgControl_37_5:any;
  _NgControlStatus_37_6:import27.Wrapper_NgControlStatus;
  _TextArea_37_7:import28.Wrapper_TextArea;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _Row_42_3:import25.Wrapper_Row;
  _text_43:any;
  _el_44:any;
  _Col_44_3:import25.Wrapper_Col;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _Col_47_3:import25.Wrapper_Col;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _Row_51_3:import25.Wrapper_Row;
  _text_52:any;
  _el_53:any;
  _Col_53_3:import25.Wrapper_Col;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _NgModel_55_4:import26.Wrapper_NgModel;
  _NgControl_55_5:any;
  _NgControlStatus_55_6:import27.Wrapper_NgControlStatus;
  _TextArea_55_7:import28.Wrapper_TextArea;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _Row_60_3:import25.Wrapper_Row;
  _text_61:any;
  _el_62:any;
  _Col_62_3:import25.Wrapper_Col;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _Col_65_3:import25.Wrapper_Col;
  _text_66:any;
  _el_67:any;
  _Col_67_3:import25.Wrapper_Col;
  _text_68:any;
  _el_69:any;
  _Col_69_3:import25.Wrapper_Col;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _Row_73_3:import25.Wrapper_Row;
  _text_74:any;
  _el_75:any;
  _Col_75_3:import25.Wrapper_Col;
  _text_76:any;
  _el_77:any;
  /*private*/ _appEl_77:import3.AppElement;
  _NgModel_77_4:import26.Wrapper_NgModel;
  _NgControl_77_5:any;
  _NgControlStatus_77_6:import27.Wrapper_NgControlStatus;
  _TextArea_77_7:import28.Wrapper_TextArea;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _Row_82_3:import25.Wrapper_Row;
  _text_83:any;
  _el_84:any;
  _Col_84_3:import25.Wrapper_Col;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _Col_87_3:import25.Wrapper_Col;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _Row_91_3:import25.Wrapper_Row;
  _text_92:any;
  _el_93:any;
  _Col_93_3:import25.Wrapper_Col;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _Col_96_3:import25.Wrapper_Col;
  _text_97:any;
  _el_98:any;
  _Col_98_3:import25.Wrapper_Col;
  _text_99:any;
  _el_100:any;
  /*private*/ _appEl_100:import3.AppElement;
  _Item_100_4:import29.Wrapper_Item;
  _ItemContent_100_5:import29.Wrapper_ItemContent;
  _query_Label_100_0:import22.QueryList<any>;
  _query_Button_100_1:import22.QueryList<any>;
  _query_Icon_100_2:import22.QueryList<any>;
  _text_101:any;
  _el_102:any;
  /*private*/ _appEl_102:import3.AppElement;
  _DateTime_102_4:import30.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_102_5:any[];
  _NgModel_102_6:import26.Wrapper_NgModel;
  _NgControl_102_7:any;
  _NgControlStatus_102_8:import27.Wrapper_NgControlStatus;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _Row_107_3:import25.Wrapper_Row;
  _text_108:any;
  _el_109:any;
  _Col_109_3:import25.Wrapper_Col;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _Col_112_3:import25.Wrapper_Col;
  _text_113:any;
  _el_114:any;
  _Col_114_3:import25.Wrapper_Col;
  _text_115:any;
  _el_116:any;
  /*private*/ _appEl_116:import3.AppElement;
  _Item_116_4:import29.Wrapper_Item;
  _ItemContent_116_5:import29.Wrapper_ItemContent;
  _query_Label_116_0:import22.QueryList<any>;
  _query_Button_116_1:import22.QueryList<any>;
  _query_Icon_116_2:import22.QueryList<any>;
  _text_117:any;
  _el_118:any;
  /*private*/ _appEl_118:import3.AppElement;
  _DateTime_118_4:import30.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_118_5:any[];
  _NgModel_118_6:import26.Wrapper_NgModel;
  _NgControl_118_7:any;
  _NgControlStatus_118_8:import27.Wrapper_NgControlStatus;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _text_122:any;
  _el_123:any;
  _Row_123_3:import25.Wrapper_Row;
  _text_124:any;
  _el_125:any;
  _Col_125_3:import25.Wrapper_Col;
  _text_126:any;
  _text_127:any;
  _el_128:any;
  _Col_128_3:import25.Wrapper_Col;
  _text_129:any;
  _text_130:any;
  _text_131:any;
  _el_132:any;
  _Row_132_3:import25.Wrapper_Row;
  _text_133:any;
  _el_134:any;
  _Col_134_3:import25.Wrapper_Col;
  _text_135:any;
  _el_136:any;
  /*private*/ _appEl_136:import3.AppElement;
  _NgModel_136_4:import26.Wrapper_NgModel;
  _NgControl_136_5:any;
  _NgControlStatus_136_6:import27.Wrapper_NgControlStatus;
  _TextArea_136_7:import28.Wrapper_TextArea;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _el_141:any;
  _Row_141_3:import25.Wrapper_Row;
  _text_142:any;
  _el_143:any;
  _Col_143_3:import25.Wrapper_Col;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _el_147:any;
  /*private*/ _appEl_147:import3.AppElement;
  _Button_147_4:import23.Wrapper_Button;
  _text_148:any;
  _text_149:any;
  _text_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _text_155:any;
  _text_156:any;
  _text_157:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AddTaskPage0,renderType_AddTaskPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import18.Wrapper_Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import19.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import19.Wrapper_Navbar(this.parentInjector.get(import34.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','font-size: 18px;');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import35.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'发布任务',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_8,'end','');
    this._ToolbarItem_8_3 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import35.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_8_0 = new import22.QueryList<any>();
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'color','blue');
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this._appEl_10 = new import3.AppElement(10,8,this,this._el_10);
    var compView_10:any = import23.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import23.Wrapper_Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','pic-button-email');
    this.renderer.setElementAttribute(this._el_12,'src','assets/img/message.png');
    this._text_13 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_10.create(this._Button_10_4.context,[([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_13
      ]
    )],(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_8]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_18 = new import3.AppElement(18,(null as any),this,this._el_18);
    var compView_18:any = import24.viewFactory_Content0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Content_18_4 = new import24.Wrapper_Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import34.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_18.initComponent(this._Content_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','contentGray');
    this.renderer.setElementAttribute(this._el_22,'padding','');
    this.renderer.setElementAttribute(this._el_22,'style','height: 670px;');
    this._Grid_22_3 = new import25.Wrapper_Grid();
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_24,'center','');
    this.renderer.setElementAttribute(this._el_24,'style','height: 44px; font-size: 14px;');
    this._Row_24_3 = new import25.Wrapper_Row();
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_26,'style','color: #4A4A4A; text-align: left;');
    this.renderer.setElementAttribute(this._el_26,'width-20','');
    this._Col_26_3 = new import25.Wrapper_Col();
    this._text_27 = this.renderer.createText(this._el_26,'任务名称',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_24,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_29,'style','color: #9B9B9B; text-align: right;');
    this.renderer.setElementAttribute(this._el_29,'width-80','');
    this._Col_29_3 = new import25.Wrapper_Col();
    this._text_30 = this.renderer.createText(this._el_29,'请为你的任务起一个名字',(null as any));
    this._text_31 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','no-padding');
    this.renderer.setElementAttribute(this._el_33,'style','height: 44px; font-size: 16px;');
    this._Row_33_3 = new import25.Wrapper_Row();
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','no-padding');
    this.renderer.setElementAttribute(this._el_35,'width-100','');
    this._Col_35_3 = new import25.Wrapper_Col();
    this._text_36 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','myInput');
    this.renderer.setElementAttribute(this._el_37,'rows','1');
    this.renderer.setElementAttribute(this._el_37,'style','height: 44px;');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import28.viewFactory_TextArea0(this.viewUtils,this.injector(37),this._appEl_37);
    this._NgModel_37_4 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_37_5 = this._NgModel_37_4.context;
    this._NgControlStatus_37_6 = new import27.Wrapper_NgControlStatus(this._NgControl_37_5);
    this._TextArea_37_7 = new import28.Wrapper_TextArea(this.parentInjector.get(import31.Config),this.parentInjector.get(import39.Form),this.parentInjector.get(import40.Item,(null as any)),this.parentInjector.get(import34.App),this.parentInjector.get(import41.Platform),new import32.ElementRef(this._el_37),this.renderer,this._Content_18_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_37_5);
    this._appEl_37.initComponent(this._TextArea_37_7.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),' ',(null as any));
    compView_37.create(this._TextArea_37_7.context,([] as any[]),(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_42,'center','');
    this.renderer.setElementAttribute(this._el_42,'style','height: 44px; font-size: 14px;');
    this._Row_42_3 = new import25.Wrapper_Row();
    this._text_43 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_44,'style','color: #4A4A4A; text-align: left;');
    this.renderer.setElementAttribute(this._el_44,'width-20','');
    this._Col_44_3 = new import25.Wrapper_Col();
    this._text_45 = this.renderer.createText(this._el_44,'任务描述',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_42,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_47,'style','color: #9B9B9B; text-align: right;');
    this.renderer.setElementAttribute(this._el_47,'width-80','');
    this._Col_47_3 = new import25.Wrapper_Col();
    this._text_48 = this.renderer.createText(this._el_47,'在这里你可以对任务进行详细的描述',(null as any));
    this._text_49 = this.renderer.createText(this._el_42,'\n      ',(null as any));
    this._text_50 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','no-padding');
    this.renderer.setElementAttribute(this._el_51,'style','height: 141px; font-size: 16px;');
    this._Row_51_3 = new import25.Wrapper_Row();
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','no-padding');
    this.renderer.setElementAttribute(this._el_53,'width-100','');
    this._Col_53_3 = new import25.Wrapper_Col();
    this._text_54 = this.renderer.createText(this._el_53,'\n          ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','myInput');
    this.renderer.setElementAttribute(this._el_55,'rows','6');
    this.renderer.setElementAttribute(this._el_55,'style','height: 141px;');
    this._appEl_55 = new import3.AppElement(55,53,this,this._el_55);
    var compView_55:any = import28.viewFactory_TextArea0(this.viewUtils,this.injector(55),this._appEl_55);
    this._NgModel_55_4 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_55_5 = this._NgModel_55_4.context;
    this._NgControlStatus_55_6 = new import27.Wrapper_NgControlStatus(this._NgControl_55_5);
    this._TextArea_55_7 = new import28.Wrapper_TextArea(this.parentInjector.get(import31.Config),this.parentInjector.get(import39.Form),this.parentInjector.get(import40.Item,(null as any)),this.parentInjector.get(import34.App),this.parentInjector.get(import41.Platform),new import32.ElementRef(this._el_55),this.renderer,this._Content_18_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_55_5);
    this._appEl_55.initComponent(this._TextArea_55_7.context,([] as any[]),compView_55);
    this._text_56 = this.renderer.createText((null as any),' ',(null as any));
    compView_55.create(this._TextArea_55_7.context,([] as any[]),(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._text_59 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_60,'center','');
    this.renderer.setElementAttribute(this._el_60,'style','height: 44px; font-size: 14px;');
    this._Row_60_3 = new import25.Wrapper_Row();
    this._text_61 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_62,'style','color: #4A4A4A; text-align: left;');
    this.renderer.setElementAttribute(this._el_62,'width-20','');
    this._Col_62_3 = new import25.Wrapper_Col();
    this._text_63 = this.renderer.createText(this._el_62,'任务地点',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_60,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_65,'width-50','');
    this._Col_65_3 = new import25.Wrapper_Col();
    this._text_66 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_60,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_67,'width-10','');
    this._Col_67_3 = new import25.Wrapper_Col();
    this._text_68 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_60,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_69,'style','color: #9B9B9B; text-align: right;');
    this.renderer.setElementAttribute(this._el_69,'width-20','');
    this._Col_69_3 = new import25.Wrapper_Col();
    this._text_70 = this.renderer.createText(this._el_69,'自动定位',(null as any));
    this._text_71 = this.renderer.createText(this._el_60,'\n      ',(null as any));
    this._text_72 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','no-padding');
    this.renderer.setElementAttribute(this._el_73,'style','height: 44px; font-size: 16px;');
    this._Row_73_3 = new import25.Wrapper_Row();
    this._text_74 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','no-padding');
    this.renderer.setElementAttribute(this._el_75,'width-100','');
    this._Col_75_3 = new import25.Wrapper_Col();
    this._text_76 = this.renderer.createText(this._el_75,'\n          ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_75,'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','myInput');
    this.renderer.setElementAttribute(this._el_77,'id','position');
    this.renderer.setElementAttribute(this._el_77,'rows','1');
    this.renderer.setElementAttribute(this._el_77,'style','height: 44px;');
    this._appEl_77 = new import3.AppElement(77,75,this,this._el_77);
    var compView_77:any = import28.viewFactory_TextArea0(this.viewUtils,this.injector(77),this._appEl_77);
    this._NgModel_77_4 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_77_5 = this._NgModel_77_4.context;
    this._NgControlStatus_77_6 = new import27.Wrapper_NgControlStatus(this._NgControl_77_5);
    this._TextArea_77_7 = new import28.Wrapper_TextArea(this.parentInjector.get(import31.Config),this.parentInjector.get(import39.Form),this.parentInjector.get(import40.Item,(null as any)),this.parentInjector.get(import34.App),this.parentInjector.get(import41.Platform),new import32.ElementRef(this._el_77),this.renderer,this._Content_18_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_77_5);
    this._appEl_77.initComponent(this._TextArea_77_7.context,([] as any[]),compView_77);
    this._text_78 = this.renderer.createText((null as any),' ',(null as any));
    compView_77.create(this._TextArea_77_7.context,([] as any[]),(null as any));
    this._text_79 = this.renderer.createText(this._el_75,'\n        ',(null as any));
    this._text_80 = this.renderer.createText(this._el_73,'\n      ',(null as any));
    this._text_81 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_82,'center','');
    this.renderer.setElementAttribute(this._el_82,'style','height: 44px; font-size: 14px;');
    this._Row_82_3 = new import25.Wrapper_Row();
    this._text_83 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_84,'style','color: #4A4A4A; text-align: left;');
    this.renderer.setElementAttribute(this._el_84,'width-20','');
    this._Col_84_3 = new import25.Wrapper_Col();
    this._text_85 = this.renderer.createText(this._el_84,'任务时间',(null as any));
    this._text_86 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_82,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_87,'style','color: #9B9B9B; text-align: right;');
    this.renderer.setElementAttribute(this._el_87,'width-80','');
    this._Col_87_3 = new import25.Wrapper_Col();
    this._text_88 = this.renderer.createText(this._el_87,'我愿意在以下时间段内观看直播',(null as any));
    this._text_89 = this.renderer.createText(this._el_82,'\n      ',(null as any));
    this._text_90 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_91,'center','');
    this.renderer.setElementAttribute(this._el_91,'style','height: 44px;');
    this._Row_91_3 = new import25.Wrapper_Row();
    this._text_92 = this.renderer.createText(this._el_91,'\n        ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_93,'style','color: #9B9B9B; text-align: center; font-size: 14px;');
    this.renderer.setElementAttribute(this._el_93,'width-33','');
    this._Col_93_3 = new import25.Wrapper_Col();
    this._text_94 = this.renderer.createText(this._el_93,'开始时间',(null as any));
    this._text_95 = this.renderer.createText(this._el_91,'\n        ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_96,'width-10','');
    this._Col_96_3 = new import25.Wrapper_Col();
    this._text_97 = this.renderer.createText(this._el_91,'\n        ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_98,'style','color: #4A4A4A; text-align: center; font-size: 18px;');
    this.renderer.setElementAttribute(this._el_98,'width-50','');
    this._Col_98_3 = new import25.Wrapper_Col();
    this._text_99 = this.renderer.createText(this._el_98,'\n          ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','item item-block');
    this.renderer.setElementAttribute(this._el_100,'no-lines','');
    this.renderer.setElementAttribute(this._el_100,'style','background-color:#F5F5F5;');
    this._appEl_100 = new import3.AppElement(100,98,this,this._el_100);
    var compView_100:any = import29.viewFactory_Item0(this.viewUtils,this.injector(100),this._appEl_100);
    this._Item_100_4 = new import29.Wrapper_Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_100),this.renderer,this.parentInjector.get(import42.ItemReorder,(null as any)));
    this._ItemContent_100_5 = new import29.Wrapper_ItemContent();
    this._query_Label_100_0 = new import22.QueryList<any>();
    this._query_Button_100_1 = new import22.QueryList<any>();
    this._query_Icon_100_2 = new import22.QueryList<any>();
    this._appEl_100.initComponent(this._Item_100_4.context,([] as any[]),compView_100);
    this._text_101 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_102 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_102,'displayFormat','YYYY-MM-DD');
    this.renderer.setElementAttribute(this._el_102,'max','2020-12-31');
    this._appEl_102 = new import3.AppElement(102,100,this,this._el_102);
    var compView_102:any = import30.viewFactory_DateTime0(this.viewUtils,this.injector(102),this._appEl_102);
    this._DateTime_102_4 = new import30.Wrapper_DateTime(this.parentInjector.get(import39.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_102),this.renderer,this._Item_100_4.context,this.parentInjector.get(import43.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_102_5 = [this._DateTime_102_4.context];
    this._NgModel_102_6 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_102_5);
    this._NgControl_102_7 = this._NgModel_102_6.context;
    this._NgControlStatus_102_8 = new import27.Wrapper_NgControlStatus(this._NgControl_102_7);
    this._appEl_102.initComponent(this._DateTime_102_4.context,([] as any[]),compView_102);
    compView_102.create(this._DateTime_102_4.context,([] as any[]),(null as any));
    this._text_103 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_100_0.reset(([] as any[]));
    this._Item_100_4.context.contentLabel = this._query_Label_100_0.first;
    compView_100.create(this._Item_100_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_101,
        this._text_103
      ]
      ),
      ([] as any[]).concat([this._el_102]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_104 = this.renderer.createText(this._el_98,'\n        ',(null as any));
    this._text_105 = this.renderer.createText(this._el_91,'\n      ',(null as any));
    this._text_106 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_107 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_107,'center','');
    this.renderer.setElementAttribute(this._el_107,'style','height: 44px;');
    this._Row_107_3 = new import25.Wrapper_Row();
    this._text_108 = this.renderer.createText(this._el_107,'\n        ',(null as any));
    this._el_109 = this.renderer.createElement(this._el_107,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_109,'style','color: #9B9B9B; text-align: center; font-size: 14px;');
    this.renderer.setElementAttribute(this._el_109,'width-33','');
    this._Col_109_3 = new import25.Wrapper_Col();
    this._text_110 = this.renderer.createText(this._el_109,'结束时间',(null as any));
    this._text_111 = this.renderer.createText(this._el_107,'\n        ',(null as any));
    this._el_112 = this.renderer.createElement(this._el_107,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_112,'width-10','');
    this._Col_112_3 = new import25.Wrapper_Col();
    this._text_113 = this.renderer.createText(this._el_107,'\n        ',(null as any));
    this._el_114 = this.renderer.createElement(this._el_107,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_114,'style','color: #4A4A4A; text-align: center; font-size: 18px;');
    this.renderer.setElementAttribute(this._el_114,'width-50','');
    this._Col_114_3 = new import25.Wrapper_Col();
    this._text_115 = this.renderer.createText(this._el_114,'\n          ',(null as any));
    this._el_116 = this.renderer.createElement(this._el_114,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_116,'class','item item-block');
    this.renderer.setElementAttribute(this._el_116,'no-lines','');
    this.renderer.setElementAttribute(this._el_116,'style','background-color:#F5F5F5;');
    this._appEl_116 = new import3.AppElement(116,114,this,this._el_116);
    var compView_116:any = import29.viewFactory_Item0(this.viewUtils,this.injector(116),this._appEl_116);
    this._Item_116_4 = new import29.Wrapper_Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_116),this.renderer,this.parentInjector.get(import42.ItemReorder,(null as any)));
    this._ItemContent_116_5 = new import29.Wrapper_ItemContent();
    this._query_Label_116_0 = new import22.QueryList<any>();
    this._query_Button_116_1 = new import22.QueryList<any>();
    this._query_Icon_116_2 = new import22.QueryList<any>();
    this._appEl_116.initComponent(this._Item_116_4.context,([] as any[]),compView_116);
    this._text_117 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_118 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_118,'displayFormat','YYYY-MM-DD');
    this.renderer.setElementAttribute(this._el_118,'max','2020-12-31');
    this._appEl_118 = new import3.AppElement(118,116,this,this._el_118);
    var compView_118:any = import30.viewFactory_DateTime0(this.viewUtils,this.injector(118),this._appEl_118);
    this._DateTime_118_4 = new import30.Wrapper_DateTime(this.parentInjector.get(import39.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_118),this.renderer,this._Item_116_4.context,this.parentInjector.get(import43.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_118_5 = [this._DateTime_118_4.context];
    this._NgModel_118_6 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_118_5);
    this._NgControl_118_7 = this._NgModel_118_6.context;
    this._NgControlStatus_118_8 = new import27.Wrapper_NgControlStatus(this._NgControl_118_7);
    this._appEl_118.initComponent(this._DateTime_118_4.context,([] as any[]),compView_118);
    compView_118.create(this._DateTime_118_4.context,([] as any[]),(null as any));
    this._text_119 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_116_0.reset(([] as any[]));
    this._Item_116_4.context.contentLabel = this._query_Label_116_0.first;
    compView_116.create(this._Item_116_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_117,
        this._text_119
      ]
      ),
      ([] as any[]).concat([this._el_118]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_120 = this.renderer.createText(this._el_114,'\n        ',(null as any));
    this._text_121 = this.renderer.createText(this._el_107,'\n      ',(null as any));
    this._text_122 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_123 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_123,'center','');
    this.renderer.setElementAttribute(this._el_123,'style','height: 44px; font-size: 14px;');
    this._Row_123_3 = new import25.Wrapper_Row();
    this._text_124 = this.renderer.createText(this._el_123,'\n        ',(null as any));
    this._el_125 = this.renderer.createElement(this._el_123,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_125,'style','color: #4A4A4A; text-align: left;');
    this.renderer.setElementAttribute(this._el_125,'width-20','');
    this._Col_125_3 = new import25.Wrapper_Col();
    this._text_126 = this.renderer.createText(this._el_125,'任务报酬',(null as any));
    this._text_127 = this.renderer.createText(this._el_123,'\n        ',(null as any));
    this._el_128 = this.renderer.createElement(this._el_123,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_128,'style','color: #9B9B9B; text-align: right;');
    this.renderer.setElementAttribute(this._el_128,'width-80','');
    this._Col_128_3 = new import25.Wrapper_Col();
    this._text_129 = this.renderer.createText(this._el_128,'我愿意为此任务支付金币',(null as any));
    this._text_130 = this.renderer.createText(this._el_123,'\n      ',(null as any));
    this._text_131 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_132,'class','no-padding');
    this.renderer.setElementAttribute(this._el_132,'style','height: 44px; font-size: 16px;');
    this._Row_132_3 = new import25.Wrapper_Row();
    this._text_133 = this.renderer.createText(this._el_132,'\n        ',(null as any));
    this._el_134 = this.renderer.createElement(this._el_132,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_134,'class','no-padding');
    this.renderer.setElementAttribute(this._el_134,'width-100','');
    this._Col_134_3 = new import25.Wrapper_Col();
    this._text_135 = this.renderer.createText(this._el_134,'\n          ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_134,'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_136,'class','myInput');
    this.renderer.setElementAttribute(this._el_136,'rows','1');
    this.renderer.setElementAttribute(this._el_136,'style','height: 44px;');
    this._appEl_136 = new import3.AppElement(136,134,this,this._el_136);
    var compView_136:any = import28.viewFactory_TextArea0(this.viewUtils,this.injector(136),this._appEl_136);
    this._NgModel_136_4 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_136_5 = this._NgModel_136_4.context;
    this._NgControlStatus_136_6 = new import27.Wrapper_NgControlStatus(this._NgControl_136_5);
    this._TextArea_136_7 = new import28.Wrapper_TextArea(this.parentInjector.get(import31.Config),this.parentInjector.get(import39.Form),this.parentInjector.get(import40.Item,(null as any)),this.parentInjector.get(import34.App),this.parentInjector.get(import41.Platform),new import32.ElementRef(this._el_136),this.renderer,this._Content_18_4.context,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_136_5);
    this._appEl_136.initComponent(this._TextArea_136_7.context,([] as any[]),compView_136);
    this._text_137 = this.renderer.createText((null as any),' ',(null as any));
    compView_136.create(this._TextArea_136_7.context,([] as any[]),(null as any));
    this._text_138 = this.renderer.createText(this._el_134,'\n        ',(null as any));
    this._text_139 = this.renderer.createText(this._el_132,'\n      ',(null as any));
    this._text_140 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_141 = this.renderer.createElement(this._el_22,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_141,'center','');
    this.renderer.setElementAttribute(this._el_141,'class','no-padding');
    this.renderer.setElementAttribute(this._el_141,'style','height: 89px;');
    this._Row_141_3 = new import25.Wrapper_Row();
    this._text_142 = this.renderer.createText(this._el_141,'\n        ',(null as any));
    this._el_143 = this.renderer.createElement(this._el_141,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_143,'class','no-padding');
    this.renderer.setElementAttribute(this._el_143,'width-100','');
    this._Col_143_3 = new import25.Wrapper_Col();
    this._text_144 = this.renderer.createText(this._el_143,'\n          ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_143,'div',(null as any));
    this.renderer.setElementAttribute(this._el_145,'style','height: 45px; background-color: #F5F5F5;');
    this._text_146 = this.renderer.createText(this._el_143,'\n          ',(null as any));
    this._el_147 = this.renderer.createElement(this._el_143,'button',(null as any));
    this.renderer.setElementAttribute(this._el_147,'block','');
    this.renderer.setElementAttribute(this._el_147,'color','blue');
    this.renderer.setElementAttribute(this._el_147,'ion-button','');
    this.renderer.setElementAttribute(this._el_147,'style','font-size: 18px; height: 44px;');
    this._appEl_147 = new import3.AppElement(147,143,this,this._el_147);
    var compView_147:any = import23.viewFactory_Button0(this.viewUtils,this.injector(147),this._appEl_147);
    this._Button_147_4 = new import23.Wrapper_Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_147),this.renderer);
    this._appEl_147.initComponent(this._Button_147_4.context,([] as any[]),compView_147);
    this._text_148 = this.renderer.createText((null as any),'确认发布',(null as any));
    compView_147.create(this._Button_147_4.context,[([] as any[]).concat([this._text_148])],(null as any));
    this._text_149 = this.renderer.createText(this._el_143,'\n        ',(null as any));
    this._text_150 = this.renderer.createText(this._el_141,'\n      ',(null as any));
    this._text_151 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_152 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_153 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_153,'style','height: 45px; background-color: #F5F5F5;');
    this._text_154 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._text_155 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_156 = this.renderer.createText((null as any),'\n  \n',(null as any));
    compView_18.create(this._Content_18_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_19,
        this._text_20,
        this._text_21,
        this._el_22,
        this._text_152,
        this._el_153,
        this._text_154,
        this._text_155,
        this._text_156
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_157 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_5 = import9.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    const subscription_0:any = this._NgModel_37_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_8 = import9.UNINITIALIZED;
    this._expr_9 = import9.UNINITIALIZED;
    this._expr_10 = import9.UNINITIALIZED;
    this._expr_11 = import9.UNINITIALIZED;
    this._expr_12 = import9.UNINITIALIZED;
    this._expr_13 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_55,'ngModelChange',this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    const subscription_1:any = this._NgModel_55_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    this._expr_16 = import9.UNINITIALIZED;
    this._expr_17 = import9.UNINITIALIZED;
    this._expr_18 = import9.UNINITIALIZED;
    this._expr_19 = import9.UNINITIALIZED;
    this._expr_20 = import9.UNINITIALIZED;
    this._expr_21 = import9.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_69,'click',this.eventHandler(this._handle_click_69_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_77,'ngModelChange',this.eventHandler(this._handle_ngModelChange_77_0.bind(this)));
    const subscription_2:any = this._NgModel_77_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_77_0.bind(this)));
    this._expr_25 = import9.UNINITIALIZED;
    this._expr_26 = import9.UNINITIALIZED;
    this._expr_27 = import9.UNINITIALIZED;
    this._expr_28 = import9.UNINITIALIZED;
    this._expr_29 = import9.UNINITIALIZED;
    this._expr_30 = import9.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_102,'ngModelChange',this.eventHandler(this._handle_ngModelChange_102_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_102,'ionChange',this.eventHandler(this._handle_ionChange_102_1.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_102,'click',this.eventHandler(this._handle_click_102_2.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_102,'keyup.space',this.eventHandler(this._handle_keyup_space_102_3.bind(this)));
    this._expr_38 = import9.UNINITIALIZED;
    const subscription_3:any = this._DateTime_102_4.context.ionChange.subscribe(this.eventHandler(this._handle_ionChange_102_1.bind(this)));
    const subscription_4:any = this._NgModel_102_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_102_0.bind(this)));
    this._expr_40 = import9.UNINITIALIZED;
    this._expr_41 = import9.UNINITIALIZED;
    this._expr_42 = import9.UNINITIALIZED;
    this._expr_43 = import9.UNINITIALIZED;
    this._expr_44 = import9.UNINITIALIZED;
    this._expr_45 = import9.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_118,'ngModelChange',this.eventHandler(this._handle_ngModelChange_118_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_118,'click',this.eventHandler(this._handle_click_118_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_118,'keyup.space',this.eventHandler(this._handle_keyup_space_118_2.bind(this)));
    this._expr_52 = import9.UNINITIALIZED;
    const subscription_5:any = this._NgModel_118_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_118_0.bind(this)));
    this._expr_54 = import9.UNINITIALIZED;
    this._expr_55 = import9.UNINITIALIZED;
    this._expr_56 = import9.UNINITIALIZED;
    this._expr_57 = import9.UNINITIALIZED;
    this._expr_58 = import9.UNINITIALIZED;
    this._expr_59 = import9.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_136,'ngModelChange',this.eventHandler(this._handle_ngModelChange_136_0.bind(this)));
    const subscription_6:any = this._NgModel_136_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_136_0.bind(this)));
    this._expr_62 = import9.UNINITIALIZED;
    this._expr_63 = import9.UNINITIALIZED;
    this._expr_64 = import9.UNINITIALIZED;
    this._expr_65 = import9.UNINITIALIZED;
    this._expr_66 = import9.UNINITIALIZED;
    this._expr_67 = import9.UNINITIALIZED;
    var disposable_13:Function = this.renderer.listen(this._el_147,'click',this.eventHandler(this._handle_click_147_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._text_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._el_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._text_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._text_155,
      this._text_156,
      this._text_157
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5,
      subscription_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import45.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_10_4.context; }
    if (((token === import46.ToolbarItem) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarItem_8_3.context; }
    if (((token === import47.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_3_4.context; }
    if (((token === import35.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_1_3.context; }
    if (((token === import48.Col) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Col_26_3.context; }
    if (((token === import48.Col) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Col_29_3.context; }
    if (((token === import48.Row) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Row_24_3.context; }
    if (((token === import49.NgModel) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgModel_37_4.context; }
    if (((token === import50.NgControl) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControl_37_5; }
    if (((token === import51.NgControlStatus) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatus_37_6.context; }
    if (((token === import52.TextArea) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._TextArea_37_7.context; }
    if (((token === import48.Col) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Col_35_3.context; }
    if (((token === import48.Row) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Row_33_3.context; }
    if (((token === import48.Col) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Col_44_3.context; }
    if (((token === import48.Col) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_47_3.context; }
    if (((token === import48.Row) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Row_42_3.context; }
    if (((token === import49.NgModel) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgModel_55_4.context; }
    if (((token === import50.NgControl) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgControl_55_5; }
    if (((token === import51.NgControlStatus) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgControlStatus_55_6.context; }
    if (((token === import52.TextArea) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._TextArea_55_7.context; }
    if (((token === import48.Col) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Col_53_3.context; }
    if (((token === import48.Row) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Row_51_3.context; }
    if (((token === import48.Col) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Col_62_3.context; }
    if (((token === import48.Col) && (65 === requestNodeIndex))) { return this._Col_65_3.context; }
    if (((token === import48.Col) && (67 === requestNodeIndex))) { return this._Col_67_3.context; }
    if (((token === import48.Col) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Col_69_3.context; }
    if (((token === import48.Row) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Row_60_3.context; }
    if (((token === import49.NgModel) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._NgModel_77_4.context; }
    if (((token === import50.NgControl) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._NgControl_77_5; }
    if (((token === import51.NgControlStatus) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._NgControlStatus_77_6.context; }
    if (((token === import52.TextArea) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._TextArea_77_7.context; }
    if (((token === import48.Col) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Col_75_3.context; }
    if (((token === import48.Row) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Row_73_3.context; }
    if (((token === import48.Col) && ((84 <= requestNodeIndex) && (requestNodeIndex <= 85)))) { return this._Col_84_3.context; }
    if (((token === import48.Col) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._Col_87_3.context; }
    if (((token === import48.Row) && ((82 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._Row_82_3.context; }
    if (((token === import48.Col) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Col_93_3.context; }
    if (((token === import48.Col) && (96 === requestNodeIndex))) { return this._Col_96_3.context; }
    if (((token === import53.DateTime) && (102 === requestNodeIndex))) { return this._DateTime_102_4.context; }
    if (((token === import54.NG_VALUE_ACCESSOR) && (102 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_102_5; }
    if (((token === import49.NgModel) && (102 === requestNodeIndex))) { return this._NgModel_102_6.context; }
    if (((token === import50.NgControl) && (102 === requestNodeIndex))) { return this._NgControl_102_7; }
    if (((token === import51.NgControlStatus) && (102 === requestNodeIndex))) { return this._NgControlStatus_102_8.context; }
    if (((token === import40.Item) && ((100 <= requestNodeIndex) && (requestNodeIndex <= 103)))) { return this._Item_100_4.context; }
    if (((token === import40.ItemContent) && ((100 <= requestNodeIndex) && (requestNodeIndex <= 103)))) { return this._ItemContent_100_5.context; }
    if (((token === import48.Col) && ((98 <= requestNodeIndex) && (requestNodeIndex <= 104)))) { return this._Col_98_3.context; }
    if (((token === import48.Row) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._Row_91_3.context; }
    if (((token === import48.Col) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._Col_109_3.context; }
    if (((token === import48.Col) && (112 === requestNodeIndex))) { return this._Col_112_3.context; }
    if (((token === import53.DateTime) && (118 === requestNodeIndex))) { return this._DateTime_118_4.context; }
    if (((token === import54.NG_VALUE_ACCESSOR) && (118 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_118_5; }
    if (((token === import49.NgModel) && (118 === requestNodeIndex))) { return this._NgModel_118_6.context; }
    if (((token === import50.NgControl) && (118 === requestNodeIndex))) { return this._NgControl_118_7; }
    if (((token === import51.NgControlStatus) && (118 === requestNodeIndex))) { return this._NgControlStatus_118_8.context; }
    if (((token === import40.Item) && ((116 <= requestNodeIndex) && (requestNodeIndex <= 119)))) { return this._Item_116_4.context; }
    if (((token === import40.ItemContent) && ((116 <= requestNodeIndex) && (requestNodeIndex <= 119)))) { return this._ItemContent_116_5.context; }
    if (((token === import48.Col) && ((114 <= requestNodeIndex) && (requestNodeIndex <= 120)))) { return this._Col_114_3.context; }
    if (((token === import48.Row) && ((107 <= requestNodeIndex) && (requestNodeIndex <= 121)))) { return this._Row_107_3.context; }
    if (((token === import48.Col) && ((125 <= requestNodeIndex) && (requestNodeIndex <= 126)))) { return this._Col_125_3.context; }
    if (((token === import48.Col) && ((128 <= requestNodeIndex) && (requestNodeIndex <= 129)))) { return this._Col_128_3.context; }
    if (((token === import48.Row) && ((123 <= requestNodeIndex) && (requestNodeIndex <= 130)))) { return this._Row_123_3.context; }
    if (((token === import49.NgModel) && ((136 <= requestNodeIndex) && (requestNodeIndex <= 137)))) { return this._NgModel_136_4.context; }
    if (((token === import50.NgControl) && ((136 <= requestNodeIndex) && (requestNodeIndex <= 137)))) { return this._NgControl_136_5; }
    if (((token === import51.NgControlStatus) && ((136 <= requestNodeIndex) && (requestNodeIndex <= 137)))) { return this._NgControlStatus_136_6.context; }
    if (((token === import52.TextArea) && ((136 <= requestNodeIndex) && (requestNodeIndex <= 137)))) { return this._TextArea_136_7.context; }
    if (((token === import48.Col) && ((134 <= requestNodeIndex) && (requestNodeIndex <= 138)))) { return this._Col_134_3.context; }
    if (((token === import48.Row) && ((132 <= requestNodeIndex) && (requestNodeIndex <= 139)))) { return this._Row_132_3.context; }
    if (((token === import45.Button) && ((147 <= requestNodeIndex) && (requestNodeIndex <= 148)))) { return this._Button_147_4.context; }
    if (((token === import48.Col) && ((143 <= requestNodeIndex) && (requestNodeIndex <= 149)))) { return this._Col_143_3.context; }
    if (((token === import48.Row) && ((141 <= requestNodeIndex) && (requestNodeIndex <= 150)))) { return this._Row_141_3.context; }
    if (((token === import48.Grid) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 151)))) { return this._Grid_22_3.context; }
    if (((token === import55.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 156)))) { return this._Content_18_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    this._ToolbarItem_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    const currVal_4:any = 'blue';
    this._Button_10_4.check_color(currVal_4,throwOnChange,false);
    if (this._Button_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    if (this._Content_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._Grid_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Row_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Col_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Col_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    this._Row_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    this._Col_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_7:any = this.context.task.taskName;
    this._NgModel_37_4.check_model(currVal_7,throwOnChange,false);
    this._NgModel_37_4.detectChangesInternal(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_6.detectChangesInternal(this,this._el_37,throwOnChange);
    this._TextArea_37_7.detectChangesInternal(this,this._el_37,throwOnChange);
    this._Row_42_3.detectChangesInternal(this,this._el_42,throwOnChange);
    this._Col_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Col_47_3.detectChangesInternal(this,this._el_47,throwOnChange);
    this._Row_51_3.detectChangesInternal(this,this._el_51,throwOnChange);
    this._Col_53_3.detectChangesInternal(this,this._el_53,throwOnChange);
    const currVal_15:any = this.context.task.taskDescription;
    this._NgModel_55_4.check_model(currVal_15,throwOnChange,false);
    this._NgModel_55_4.detectChangesInternal(this,this._el_55,throwOnChange);
    this._NgControlStatus_55_6.detectChangesInternal(this,this._el_55,throwOnChange);
    this._TextArea_55_7.detectChangesInternal(this,this._el_55,throwOnChange);
    this._Row_60_3.detectChangesInternal(this,this._el_60,throwOnChange);
    this._Col_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    this._Col_65_3.detectChangesInternal(this,this._el_65,throwOnChange);
    this._Col_67_3.detectChangesInternal(this,this._el_67,throwOnChange);
    this._Col_69_3.detectChangesInternal(this,this._el_69,throwOnChange);
    this._Row_73_3.detectChangesInternal(this,this._el_73,throwOnChange);
    this._Col_75_3.detectChangesInternal(this,this._el_75,throwOnChange);
    const currVal_24:any = this.context.task.taskPosition;
    this._NgModel_77_4.check_model(currVal_24,throwOnChange,false);
    this._NgModel_77_4.detectChangesInternal(this,this._el_77,throwOnChange);
    this._NgControlStatus_77_6.detectChangesInternal(this,this._el_77,throwOnChange);
    this._TextArea_77_7.detectChangesInternal(this,this._el_77,throwOnChange);
    this._Row_82_3.detectChangesInternal(this,this._el_82,throwOnChange);
    this._Col_84_3.detectChangesInternal(this,this._el_84,throwOnChange);
    this._Col_87_3.detectChangesInternal(this,this._el_87,throwOnChange);
    this._Row_91_3.detectChangesInternal(this,this._el_91,throwOnChange);
    this._Col_93_3.detectChangesInternal(this,this._el_93,throwOnChange);
    this._Col_96_3.detectChangesInternal(this,this._el_96,throwOnChange);
    this._Col_98_3.detectChangesInternal(this,this._el_98,throwOnChange);
    if (this._Item_100_4.detectChangesInternal(this,this._el_100,throwOnChange)) { this._appEl_100.componentView.markAsCheckOnce(); }
    this._ItemContent_100_5.detectChangesInternal(this,this._el_100,throwOnChange);
    const currVal_35:any = this.context.minStartTime;
    this._DateTime_102_4.check_min(currVal_35,throwOnChange,false);
    const currVal_36:any = '2020-12-31';
    this._DateTime_102_4.check_max(currVal_36,throwOnChange,false);
    const currVal_37:any = 'YYYY-MM-DD';
    this._DateTime_102_4.check_displayFormat(currVal_37,throwOnChange,false);
    this._DateTime_102_4.detectChangesInternal(this,this._el_102,throwOnChange);
    const currVal_39:any = this.context.task.taskStartTime;
    this._NgModel_102_6.check_model(currVal_39,throwOnChange,false);
    this._NgModel_102_6.detectChangesInternal(this,this._el_102,throwOnChange);
    this._NgControlStatus_102_8.detectChangesInternal(this,this._el_102,throwOnChange);
    this._Row_107_3.detectChangesInternal(this,this._el_107,throwOnChange);
    this._Col_109_3.detectChangesInternal(this,this._el_109,throwOnChange);
    this._Col_112_3.detectChangesInternal(this,this._el_112,throwOnChange);
    this._Col_114_3.detectChangesInternal(this,this._el_114,throwOnChange);
    if (this._Item_116_4.detectChangesInternal(this,this._el_116,throwOnChange)) { this._appEl_116.componentView.markAsCheckOnce(); }
    this._ItemContent_116_5.detectChangesInternal(this,this._el_116,throwOnChange);
    const currVal_49:any = this.context.minEndTime;
    this._DateTime_118_4.check_min(currVal_49,throwOnChange,false);
    const currVal_50:any = '2020-12-31';
    this._DateTime_118_4.check_max(currVal_50,throwOnChange,false);
    const currVal_51:any = 'YYYY-MM-DD';
    this._DateTime_118_4.check_displayFormat(currVal_51,throwOnChange,false);
    this._DateTime_118_4.detectChangesInternal(this,this._el_118,throwOnChange);
    const currVal_53:any = this.context.task.taskEndTime;
    this._NgModel_118_6.check_model(currVal_53,throwOnChange,false);
    this._NgModel_118_6.detectChangesInternal(this,this._el_118,throwOnChange);
    this._NgControlStatus_118_8.detectChangesInternal(this,this._el_118,throwOnChange);
    this._Row_123_3.detectChangesInternal(this,this._el_123,throwOnChange);
    this._Col_125_3.detectChangesInternal(this,this._el_125,throwOnChange);
    this._Col_128_3.detectChangesInternal(this,this._el_128,throwOnChange);
    this._Row_132_3.detectChangesInternal(this,this._el_132,throwOnChange);
    this._Col_134_3.detectChangesInternal(this,this._el_134,throwOnChange);
    const currVal_61:any = this.context.task.taskReward;
    this._NgModel_136_4.check_model(currVal_61,throwOnChange,false);
    this._NgModel_136_4.detectChangesInternal(this,this._el_136,throwOnChange);
    this._NgControlStatus_136_6.detectChangesInternal(this,this._el_136,throwOnChange);
    this._TextArea_136_7.detectChangesInternal(this,this._el_136,throwOnChange);
    this._Row_141_3.detectChangesInternal(this,this._el_141,throwOnChange);
    this._Col_143_3.detectChangesInternal(this,this._el_143,throwOnChange);
    const currVal_69:any = '';
    this._Button_147_4.check_block(currVal_69,throwOnChange,false);
    const currVal_70:any = 'blue';
    this._Button_147_4.check_color(currVal_70,throwOnChange,false);
    if (this._Button_147_4.detectChangesInternal(this,this._el_147,throwOnChange)) { this._appEl_147.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_8_0.dirty) {
        this._query_Button_8_0.reset([this._Button_10_4.context]);
        this._ToolbarItem_8_3.context._buttons = this._query_Button_8_0;
        this._query_Button_8_0.notifyOnChanges();
      }
      if (this._query_Button_100_1.dirty) {
        this._query_Button_100_1.reset(([] as any[]));
        this._Item_100_4.context._buttons = this._query_Button_100_1;
        this._query_Button_100_1.notifyOnChanges();
      }
      if (this._query_Icon_100_2.dirty) {
        this._query_Icon_100_2.reset(([] as any[]));
        this._Item_100_4.context._icons = this._query_Icon_100_2;
        this._query_Icon_100_2.notifyOnChanges();
      }
      if (this._query_Button_116_1.dirty) {
        this._query_Button_116_1.reset(([] as any[]));
        this._Item_116_4.context._buttons = this._query_Button_116_1;
        this._query_Button_116_1.notifyOnChanges();
      }
      if (this._query_Icon_116_2.dirty) {
        this._query_Icon_116_2.reset(([] as any[]));
        this._Item_116_4.context._icons = this._query_Icon_116_2;
        this._query_Icon_116_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.context.ngAfterContentInit(); }
      this._TextArea_37_7.context.ngAfterContentChecked();
      this._TextArea_55_7.context.ngAfterContentChecked();
      this._TextArea_77_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._DateTime_102_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_100_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_118_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_116_4.context.ngAfterContentInit(); }
      this._TextArea_136_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Button_147_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Content_18_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._NgControlStatus_37_6.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_37_6.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_37_6.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_37_6.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_37_6.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_37_6.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._NgControlStatus_55_6.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_55,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_55_6.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_55,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_55_6.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_55,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_55_6.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_55,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_55_6.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_55,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_55_6.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_55,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_25:any = this._NgControlStatus_77_6.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_77,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_77_6.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_77,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_77_6.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_77,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_77_6.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_77,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_77_6.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_77,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_77_6.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_77,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_38:any = this._DateTime_102_4.context._disabled;
    if (import6.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_102,'datetime-disabled',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_40:any = this._NgControlStatus_102_8.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_102,'ng-untouched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_102_8.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_102,'ng-touched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_102_8.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_102,'ng-pristine',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_102_8.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_102,'ng-dirty',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_102_8.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_102,'ng-valid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_102_8.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_102,'ng-invalid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_52:any = this._DateTime_118_4.context._disabled;
    if (import6.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_118,'datetime-disabled',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_54:any = this._NgControlStatus_118_8.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_118,'ng-untouched',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_118_8.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_118,'ng-touched',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_118_8.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_118,'ng-pristine',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_118_8.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_118,'ng-dirty',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_118_8.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_118,'ng-valid',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_118_8.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_118,'ng-invalid',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_62:any = this._NgControlStatus_136_6.context.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_136,'ng-untouched',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this._NgControlStatus_136_6.context.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_136,'ng-touched',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_136_6.context.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_136,'ng-pristine',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_136_6.context.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_136,'ng-dirty',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_136_6.context.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_136,'ng-valid',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_136_6.context.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_136,'ng-invalid',currVal_67);
      this._expr_67 = currVal_67;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_37_4.context.ngOnDestroy();
    this._TextArea_37_7.context.ngOnDestroy();
    this._NgModel_55_4.context.ngOnDestroy();
    this._TextArea_55_7.context.ngOnDestroy();
    this._NgModel_77_4.context.ngOnDestroy();
    this._TextArea_77_7.context.ngOnDestroy();
    this._DateTime_102_4.context.ngOnDestroy();
    this._NgModel_102_6.context.ngOnDestroy();
    this._DateTime_118_4.context.ngOnDestroy();
    this._NgModel_118_6.context.ngOnDestroy();
    this._NgModel_136_4.context.ngOnDestroy();
    this._TextArea_136_7.context.ngOnDestroy();
    this._Content_18_4.context.ngOnDestroy();
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onMessage()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_55_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskDescription = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_69_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.autoPosition()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_77_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskPosition = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_102_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskStartTime = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionChange_102_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateEndTime()) !== false);
    return (true && pd_0);
  }
  private _handle_click_102_2($event:any):boolean {
    this._appEl_102.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_102_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_102_3($event:any):boolean {
    this._appEl_102.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_102_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_118_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskEndTime = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_118_1($event:any):boolean {
    this._appEl_118.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_118_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_118_2($event:any):boolean {
    this._appEl_118.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_118_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_136_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.task.taskReward = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_147_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.checkTask()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AddTaskPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AddTaskPage> {
  if ((renderType_AddTaskPage === (null as any))) { (renderType_AddTaskPage = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,styles_AddTaskPage,{})); }
  return new _View_AddTaskPage0(viewUtils,parentInjector,declarationEl);
}