/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './account-not-logged-in';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from 'ionic-angular/components/button/button';
import * as import34 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import35 from 'ionic-angular/components/navbar/navbar';
import * as import36 from 'ionic-angular/components/grid/grid';
import * as import37 from 'ionic-angular/components/slides/slides';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from 'ionic-angular/components/list/list';
import * as import40 from 'ionic-angular/components/content/content';
import * as import41 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from 'ionic-angular/components/item/item-reorder';
import * as import44 from 'ionic-angular/components/item/item';
export class Wrapper_AccountNotLoggedInPage {
  context:import0.AccountNotLoggedInPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.AccountNotLoggedInPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AccountNotLoggedInPage_Host:import2.RenderComponentType = (null as any);
class _View_AccountNotLoggedInPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AccountNotLoggedInPage_0_4:Wrapper_AccountNotLoggedInPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountNotLoggedInPage_Host0,renderType_AccountNotLoggedInPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-account-not-logged-in',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AccountNotLoggedInPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AccountNotLoggedInPage_0_4 = new Wrapper_AccountNotLoggedInPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._AccountNotLoggedInPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AccountNotLoggedInPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AccountNotLoggedInPage) && (0 === requestNodeIndex))) { return this._AccountNotLoggedInPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AccountNotLoggedInPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AccountNotLoggedInPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AccountNotLoggedInPage_Host === (null as any))) { (renderType_AccountNotLoggedInPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AccountNotLoggedInPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AccountNotLoggedInPageNgFactory:import11.ComponentFactory<import0.AccountNotLoggedInPage> = new import11.ComponentFactory<import0.AccountNotLoggedInPage>('page-account-not-logged-in',viewFactory_AccountNotLoggedInPage_Host0,import0.AccountNotLoggedInPage);
const styles_AccountNotLoggedInPage:any[] = ([] as any[]);
var renderType_AccountNotLoggedInPage:import2.RenderComponentType = (null as any);
class _View_AccountNotLoggedInPage0 extends import1.AppView<import0.AccountNotLoggedInPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import14.Wrapper_ToolbarItem;
  _query_Button_5_0:import15.QueryList<any>;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Button_7_4:import16.Wrapper_Button;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Content_15_4:import17.Wrapper_Content;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Slides_17_4:import18.Wrapper_Slides;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Slide_19_4:import18.Wrapper_Slide;
  _text_20:any;
  _el_21:any;
  _Row_21_3:import19.Wrapper_Row;
  _text_22:any;
  _el_23:any;
  _Col_23_3:import19.Wrapper_Col;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Row_27_3:import19.Wrapper_Row;
  _text_28:any;
  _el_29:any;
  _Col_29_3:import19.Wrapper_Col;
  _text_30:any;
  _el_31:any;
  _Col_31_3:import19.Wrapper_Col;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _Col_39_3:import19.Wrapper_Col;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _Row_42_3:import19.Wrapper_Row;
  _text_43:any;
  _el_44:any;
  _Col_44_3:import19.Wrapper_Col;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Button_46_4:import16.Wrapper_Button;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _Row_51_3:import19.Wrapper_Row;
  _text_52:any;
  _el_53:any;
  _Col_53_3:import19.Wrapper_Col;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _List_62_3:import20.Wrapper_List;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import3.AppElement;
  _TemplateRef_64_5:any;
  _NgFor_64_6:import21.Wrapper_NgFor;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountNotLoggedInPage0,renderType_AccountNotLoggedInPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_5,'end','');
    this._ToolbarItem_5_3 = new import14.Wrapper_ToolbarItem(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import15.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'color','blue');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import16.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','pic-button-email');
    this.renderer.setElementAttribute(this._el_9,'src','assets/img/message.png');
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_7.create(this._Button_7_4.context,[([] as any[]).concat([
        this._text_8,
        this._el_9,
        this._text_10
      ]
    )],(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([
        this._text_4,
        this._text_12
      ]
      )
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','contentGray');
    this._appEl_15 = new import3.AppElement(15,(null as any),this,this._el_15);
    var compView_15:any = import17.viewFactory_Content0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Content_15_4 = new import17.Wrapper_Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_15.initComponent(this._Content_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-slides',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','blue-pane');
    this._appEl_17 = new import3.AppElement(17,15,this,this._el_17);
    var compView_17:any = import18.viewFactory_Slides0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Slides_17_4 = new import18.Wrapper_Slides(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Slides_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this._appEl_19 = new import3.AppElement(19,17,this,this._el_19);
    var compView_19:any = import18.viewFactory_Slide0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Slide_19_4 = new import18.Wrapper_Slide(new import23.ElementRef(this._el_19),this._Slides_17_4.context);
    this._appEl_19.initComponent(this._Slide_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_21,'center','');
    this._Row_21_3 = new import19.Wrapper_Row();
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-col',(null as any));
    this._Col_23_3 = new import19.Wrapper_Col();
    this._el_24 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_27,'center','');
    this._Row_27_3 = new import19.Wrapper_Row();
    this._text_28 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_29,'width-40','');
    this._Col_29_3 = new import19.Wrapper_Col();
    this._text_30 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_31,'width-20','');
    this._Col_31_3 = new import19.Wrapper_Col();
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','image');
    this._text_34 = this.renderer.createText(this._el_33,'\n              ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'img',(null as any));
    this.renderer.setElementAttribute(this._el_35,'align','middle');
    this.renderer.setElementAttribute(this._el_35,'src','assets/img/0.png');
    this._text_36 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._text_38 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_39,'width-40','');
    this._Col_39_3 = new import19.Wrapper_Col();
    this._text_40 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_42,'center','');
    this._Row_42_3 = new import19.Wrapper_Row();
    this._text_43 = this.renderer.createText(this._el_42,'\n            ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'ion-col',(null as any));
    this._Col_44_3 = new import19.Wrapper_Col();
    this._text_45 = this.renderer.createText(this._el_44,'\n              ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'button',(null as any));
    this.renderer.setElementAttribute(this._el_46,'color','#5495E3');
    this.renderer.setElementAttribute(this._el_46,'ion-button','');
    this._appEl_46 = new import3.AppElement(46,44,this,this._el_46);
    var compView_46:any = import16.viewFactory_Button0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Button_46_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_46),this.renderer);
    this._appEl_46.initComponent(this._Button_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n                账户登录\n              ',(null as any));
    compView_46.create(this._Button_46_4.context,[([] as any[]).concat([this._text_47])],(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n          ',(null as any));
    this._text_49 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_51,'center','');
    this._Row_51_3 = new import19.Wrapper_Row();
    this._text_52 = this.renderer.createText(this._el_51,'\n          ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'ion-col',(null as any));
    this._Col_53_3 = new import19.Wrapper_Col();
    this._el_54 = this.renderer.createElement(this._el_53,'br',(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_19.create(this._Slide_19_4.context,[([] as any[]).concat([
        this._text_20,
        this._el_21,
        this._text_26,
        this._el_27,
        this._text_41,
        this._el_42,
        this._text_50,
        this._el_51,
        this._text_56,
        this._text_57
      ]
    )],(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_17.create(this._Slides_17_4.context,[([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_58
      ]
    )],(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n    \n    ',(null as any));
    this._el_60 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'style','height: 10px; background-color: #F5F5F5;');
    this._text_61 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_62,'no-lines','');
    this._List_62_3 = new import20.Wrapper_List(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_62),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_63 = this.renderer.createText(this._el_62,'\n      ',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_64 = new import3.AppElement(64,62,this,this._anchor_64);
    this._TemplateRef_64_5 = new import31.TemplateRef_(this._appEl_64,viewFactory_AccountNotLoggedInPage1);
    this._NgFor_64_6 = new import21.Wrapper_NgFor(this._appEl_64.vcRef,this._TemplateRef_64_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_65 = this.renderer.createText(this._el_62,'\n    ',(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_15.create(this._Content_15_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_59,
        this._el_60,
        this._text_61,
        this._el_62,
        this._text_66
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_67 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_46,'click',this.eventHandler(this._handle_click_46_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._text_66,
      this._text_67
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_7_4.context; }
    if (((token === import34.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3.context; }
    if (((token === import35.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_3_4.context; }
    if (((token === import26.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Header_1_3.context; }
    if (((token === import36.Col) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Col_23_3.context; }
    if (((token === import36.Row) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Row_21_3.context; }
    if (((token === import36.Col) && (29 === requestNodeIndex))) { return this._Col_29_3.context; }
    if (((token === import36.Col) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Col_31_3.context; }
    if (((token === import36.Col) && (39 === requestNodeIndex))) { return this._Col_39_3.context; }
    if (((token === import36.Row) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Row_27_3.context; }
    if (((token === import33.Button) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Button_46_4.context; }
    if (((token === import36.Col) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_44_3.context; }
    if (((token === import36.Row) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Row_42_3.context; }
    if (((token === import36.Col) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Col_53_3.context; }
    if (((token === import36.Row) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Row_51_3.context; }
    if (((token === import37.Slide) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Slide_19_4.context; }
    if (((token === import37.Slides) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Slides_17_4.context; }
    if (((token === import31.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import38.NgFor) && (64 === requestNodeIndex))) { return this._NgFor_64_6.context; }
    if (((token === import39.List) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._List_62_3.context; }
    if (((token === import40.Content) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Content_15_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    this._ToolbarItem_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_4:any = 'blue';
    this._Button_7_4.check_color(currVal_4,throwOnChange,false);
    if (this._Button_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    if (this._Content_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    if (this._Slides_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    if (this._Slide_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._Row_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Col_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Row_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    this._Col_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    this._Col_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Col_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    this._Row_42_3.detectChangesInternal(this,this._el_42,throwOnChange);
    this._Col_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_7:any = '#5495E3';
    this._Button_46_4.check_color(currVal_7,throwOnChange,false);
    if (this._Button_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this._Row_51_3.detectChangesInternal(this,this._el_51,throwOnChange);
    this._Col_53_3.detectChangesInternal(this,this._el_53,throwOnChange);
    this._List_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    const currVal_8:any = this.context.items;
    this._NgFor_64_6.check_ngForOf(currVal_8,throwOnChange,false);
    this._NgFor_64_6.detectChangesInternal(this,this._anchor_64,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_7_4.context]);
        this._ToolbarItem_5_3.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_7_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_46_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Content_15_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_15,'statusbar-padding',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Slide_19_4.context.ngOnDestroy();
    this._Content_15_4.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onMessage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_46_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onLogIn()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AccountNotLoggedInPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AccountNotLoggedInPage> {
  if ((renderType_AccountNotLoggedInPage === (null as any))) { (renderType_AccountNotLoggedInPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_AccountNotLoggedInPage,{})); }
  return new _View_AccountNotLoggedInPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AccountNotLoggedInPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import41.Wrapper_Item;
  _ItemContent_2_5:import41.Wrapper_ItemContent;
  _query_Label_2_0:import15.QueryList<any>;
  _query_Button_2_1:import15.QueryList<any>;
  _query_Icon_2_2:import15.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountNotLoggedInPage1,renderType_AccountNotLoggedInPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','paddingItem item item-block');
    this.renderer.setElementAttribute(this._el_2,'detail-push','');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import41.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import41.Wrapper_Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import43.ItemReorder,(null as any)));
    this._ItemContent_2_5 = new import41.Wrapper_ItemContent();
    this._query_Label_2_0 = new import15.QueryList<any>();
    this._query_Button_2_1 = new import15.QueryList<any>();
    this._query_Icon_2_2 = new import15.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','height: 2px; background-color: #F5F5F5;');
    this._text_6 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import44.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'\n          ',this.context.$implicit.note,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemTapped($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AccountNotLoggedInPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AccountNotLoggedInPage1(viewUtils,parentInjector,declarationEl);
}