/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './account-logged-in';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../providers/storage';
import * as import5 from '../../providers/user-data';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-params';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import25 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/components/grid/grid';
import * as import42 from 'ionic-angular/components/slides/slides';
import * as import43 from '@angular/common/src/directives/ng_for';
import * as import44 from 'ionic-angular/components/list/list';
import * as import45 from 'ionic-angular/components/typography/typography';
import * as import46 from 'ionic-angular/components/content/content';
import * as import47 from '@angular/core/src/security';
import * as import48 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import49 from 'ionic-angular/util/form';
import * as import50 from 'ionic-angular/components/item/item-reorder';
import * as import51 from 'ionic-angular/components/item/item';
export class Wrapper_AccountLoggedInPage {
  context:import0.AccountLoggedInPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.AccountLoggedInPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AccountLoggedInPage_Host:import2.RenderComponentType = (null as any);
class _View_AccountLoggedInPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Storage_0_4:import4.Storage;
  _UserData_0_5:import5.UserData;
  _AccountLoggedInPage_0_6:Wrapper_AccountLoggedInPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountLoggedInPage_Host0,renderType_AccountLoggedInPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-account-logged-in',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AccountLoggedInPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Storage_0_4 = new import4.Storage();
    this._UserData_0_5 = new import5.UserData(this.parentInjector.get(import10.Http));
    this._AccountLoggedInPage_0_6 = new Wrapper_AccountLoggedInPage(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.AlertController),this.parentInjector.get(import13.NavParams),this._Storage_0_4,this._UserData_0_5);
    this._appEl_0.initComponent(this._AccountLoggedInPage_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._AccountLoggedInPage_0_6.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.Storage) && (0 === requestNodeIndex))) { return this._Storage_0_4; }
    if (((token === import5.UserData) && (0 === requestNodeIndex))) { return this._UserData_0_5; }
    if (((token === import0.AccountLoggedInPage) && (0 === requestNodeIndex))) { return this._AccountLoggedInPage_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AccountLoggedInPage_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AccountLoggedInPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AccountLoggedInPage_Host === (null as any))) { (renderType_AccountLoggedInPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AccountLoggedInPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AccountLoggedInPageNgFactory:import15.ComponentFactory<import0.AccountLoggedInPage> = new import15.ComponentFactory<import0.AccountLoggedInPage>('page-account-logged-in',viewFactory_AccountLoggedInPage_Host0,import0.AccountLoggedInPage);
const styles_AccountLoggedInPage:any[] = ([] as any[]);
var renderType_AccountLoggedInPage:import2.RenderComponentType = (null as any);
class _View_AccountLoggedInPage0 extends import1.AppView<import0.AccountLoggedInPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import16.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import17.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import18.Wrapper_ToolbarItem;
  _query_Button_5_0:import19.QueryList<any>;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Button_7_4:import20.Wrapper_Button;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Content_20_4:import21.Wrapper_Content;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _Slides_22_4:import22.Wrapper_Slides;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Slide_24_4:import22.Wrapper_Slide;
  _text_25:any;
  _el_26:any;
  _Row_26_3:import23.Wrapper_Row;
  _text_27:any;
  _el_28:any;
  _Col_28_3:import23.Wrapper_Col;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _Row_32_3:import23.Wrapper_Row;
  _text_33:any;
  _el_34:any;
  _Col_34_3:import23.Wrapper_Col;
  _text_35:any;
  _el_36:any;
  _Col_36_3:import23.Wrapper_Col;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _Col_41_3:import23.Wrapper_Col;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _Row_44_3:import23.Wrapper_Row;
  _text_45:any;
  _el_46:any;
  _Col_46_3:import23.Wrapper_Col;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _Row_61_3:import23.Wrapper_Row;
  _text_62:any;
  _el_63:any;
  _Col_63_3:import23.Wrapper_Col;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _List_71_3:import24.Wrapper_List;
  _text_72:any;
  _anchor_73:any;
  /*private*/ _appEl_73:import3.AppElement;
  _TemplateRef_73_5:any;
  _NgFor_73_6:import25.Wrapper_NgFor;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _anchor_77:any;
  /*private*/ _appEl_77:import3.AppElement;
  _TemplateRef_77_5:any;
  _NgFor_77_6:import25.Wrapper_NgFor;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  /*private*/ _appEl_80:import3.AppElement;
  _Button_80_4:import20.Wrapper_Button;
  _el_81:any;
  _Typography_81_3:import26.Wrapper_Typography;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountLoggedInPage0,renderType_AccountLoggedInPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import16.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','blue');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import17.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import17.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_5,'end','');
    this._ToolbarItem_5_3 = new import18.Wrapper_ToolbarItem(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import19.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'color','blue');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import20.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import20.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'img',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','pic-button-email');
    this.renderer.setElementAttribute(this._el_11,'src','assets/img/message.png');
    this._text_12 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_7.create(this._Button_7_4.context,[([] as any[]).concat([
        this._text_8,
        this._el_9,
        this._text_15
      ]
    )],(null as any));
    this._text_16 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([
        this._text_4,
        this._text_17
      ]
      )
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','contentGray');
    this._appEl_20 = new import3.AppElement(20,(null as any),this,this._el_20);
    var compView_20:any = import21.viewFactory_Content0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Content_20_4 = new import21.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_20.initComponent(this._Content_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-slides',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','blue-pane');
    this._appEl_22 = new import3.AppElement(22,20,this,this._el_22);
    var compView_22:any = import22.viewFactory_Slides0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Slides_22_4 = new import22.Wrapper_Slides(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_22),this.renderer);
    this._appEl_22.initComponent(this._Slides_22_4.context,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this._appEl_24 = new import3.AppElement(24,22,this,this._el_24);
    var compView_24:any = import22.viewFactory_Slide0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Slide_24_4 = new import22.Wrapper_Slide(new import28.ElementRef(this._el_24),this._Slides_22_4.context);
    this._appEl_24.initComponent(this._Slide_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_26,'center','');
    this._Row_26_3 = new import23.Wrapper_Row();
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'ion-col',(null as any));
    this._Col_28_3 = new import23.Wrapper_Col();
    this._el_29 = this.renderer.createElement(this._el_28,'br',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_32,'center','');
    this._Row_32_3 = new import23.Wrapper_Row();
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_34,'width-40','');
    this._Col_34_3 = new import23.Wrapper_Col();
    this._text_35 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_32,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_36,'width-20','');
    this._Col_36_3 = new import23.Wrapper_Col();
    this._text_37 = this.renderer.createText(this._el_36,'\n              ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'img',(null as any));
    this.renderer.setElementAttribute(this._el_38,'style','border-radius: 40px;');
    this._text_39 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_40 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_32,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_41,'width-40','');
    this._Col_41_3 = new import23.Wrapper_Col();
    this._text_42 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_44,'center','');
    this._Row_44_3 = new import23.Wrapper_Row();
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'ion-col',(null as any));
    this._Col_46_3 = new import23.Wrapper_Col();
    this._text_47 = this.renderer.createText(this._el_46,'\n              ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','userInfo');
    this._text_49 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'span',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','userName');
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_48,'br',(null as any));
    this._text_54 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_48,'span',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','userDetail');
    this._text_56 = this.renderer.createText(this._el_55,'',(null as any));
    this._text_57 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_58 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_44,'\n          ',(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_61 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_61,'center','');
    this._Row_61_3 = new import23.Wrapper_Row();
    this._text_62 = this.renderer.createText(this._el_61,'\n            ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'ion-col',(null as any));
    this._Col_63_3 = new import23.Wrapper_Col();
    this._el_64 = this.renderer.createElement(this._el_63,'br',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n          ',(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_24.create(this._Slide_24_4.context,[([] as any[]).concat([
        this._text_25,
        this._el_26,
        this._text_31,
        this._el_32,
        this._text_43,
        this._el_44,
        this._text_60,
        this._el_61,
        this._text_66
      ]
    )],(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_22.create(this._Slides_22_4.context,[([] as any[]).concat([
        this._text_23,
        this._el_24,
        this._text_67
      ]
    )],(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_69 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_69,'style','height: 10px; background-color: #F5F5F5;');
    this._text_70 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_71,'no-lines','');
    this._List_71_3 = new import24.Wrapper_List(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_71),this.renderer,this.parentInjector.get(import35.GestureController));
    this._text_72 = this.renderer.createText(this._el_71,'\n      ',(null as any));
    this._anchor_73 = this.renderer.createTemplateAnchor(this._el_71,(null as any));
    this._appEl_73 = new import3.AppElement(73,71,this,this._anchor_73);
    this._TemplateRef_73_5 = new import36.TemplateRef_(this._appEl_73,viewFactory_AccountLoggedInPage1);
    this._NgFor_73_6 = new import25.Wrapper_NgFor(this._appEl_73.vcRef,this._TemplateRef_73_5,this.parentInjector.get(import37.IterableDiffers),this.ref);
    this._text_74 = this.renderer.createText(this._el_71,'\n      ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_71,'div',(null as any));
    this.renderer.setElementAttribute(this._el_75,'style','height: 6px; background-color: #F5F5F5;');
    this._text_76 = this.renderer.createText(this._el_71,'\n      ',(null as any));
    this._anchor_77 = this.renderer.createTemplateAnchor(this._el_71,(null as any));
    this._appEl_77 = new import3.AppElement(77,71,this,this._anchor_77);
    this._TemplateRef_77_5 = new import36.TemplateRef_(this._appEl_77,viewFactory_AccountLoggedInPage2);
    this._NgFor_77_6 = new import25.Wrapper_NgFor(this._appEl_77.vcRef,this._TemplateRef_77_5,this.parentInjector.get(import37.IterableDiffers),this.ref);
    this._text_78 = this.renderer.createText(this._el_71,'\n    ',(null as any));
    this._text_79 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_80 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_80,'color','white');
    this.renderer.setElementAttribute(this._el_80,'full','');
    this.renderer.setElementAttribute(this._el_80,'ion-button','');
    this._appEl_80 = new import3.AppElement(80,20,this,this._el_80);
    var compView_80:any = import20.viewFactory_Button0(this.viewUtils,this.injector(80),this._appEl_80);
    this._Button_80_4 = new import20.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_80),this.renderer);
    this._appEl_80.initComponent(this._Button_80_4.context,([] as any[]),compView_80);
    this._el_81 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_81,'color','blue');
    this._Typography_81_3 = new import26.Wrapper_Typography(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_81),this.renderer,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'退出登录',(null as any));
    compView_80.create(this._Button_80_4.context,[([] as any[]).concat([this._el_81])],(null as any));
    this._text_83 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_84 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_85 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_20.create(this._Content_20_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_21,
        this._el_22,
        this._text_68,
        this._el_69,
        this._text_70,
        this._el_71,
        this._text_79,
        this._el_80,
        this._text_83,
        this._el_84,
        this._text_85
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_86 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_5 = import9.UNINITIALIZED;
    this._expr_6 = import9.UNINITIALIZED;
    this._expr_7 = import9.UNINITIALIZED;
    this._expr_8 = import9.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_80,'click',this.eventHandler(this._handle_click_80_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._anchor_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._anchor_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Button_7_4.context; }
    if (((token === import39.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ToolbarItem_5_3.context; }
    if (((token === import40.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Navbar_3_4.context; }
    if (((token === import31.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Header_1_3.context; }
    if (((token === import41.Col) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Col_28_3.context; }
    if (((token === import41.Row) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Row_26_3.context; }
    if (((token === import41.Col) && (34 === requestNodeIndex))) { return this._Col_34_3.context; }
    if (((token === import41.Col) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Col_36_3.context; }
    if (((token === import41.Col) && (41 === requestNodeIndex))) { return this._Col_41_3.context; }
    if (((token === import41.Row) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Row_32_3.context; }
    if (((token === import41.Col) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Col_46_3.context; }
    if (((token === import41.Row) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Row_44_3.context; }
    if (((token === import41.Col) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Col_63_3.context; }
    if (((token === import41.Row) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Row_61_3.context; }
    if (((token === import42.Slide) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Slide_24_4.context; }
    if (((token === import42.Slides) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Slides_22_4.context; }
    if (((token === import36.TemplateRef) && (73 === requestNodeIndex))) { return this._TemplateRef_73_5; }
    if (((token === import43.NgFor) && (73 === requestNodeIndex))) { return this._NgFor_73_6.context; }
    if (((token === import36.TemplateRef) && (77 === requestNodeIndex))) { return this._TemplateRef_77_5; }
    if (((token === import43.NgFor) && (77 === requestNodeIndex))) { return this._NgFor_77_6.context; }
    if (((token === import44.List) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._List_71_3.context; }
    if (((token === import45.Typography) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Typography_81_3.context; }
    if (((token === import38.Button) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Button_80_4.context; }
    if (((token === import46.Content) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 85)))) { return this._Content_20_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'blue';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    this._ToolbarItem_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_4:any = 'blue';
    this._Button_7_4.check_color(currVal_4,throwOnChange,false);
    if (this._Button_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    if (this._Content_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    if (this._Slides_22_4.detectChangesInternal(this,this._el_22,throwOnChange)) { this._appEl_22.componentView.markAsCheckOnce(); }
    if (this._Slide_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._Row_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Col_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    this._Row_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    this._Col_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Col_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    this._Col_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Row_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Col_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Row_61_3.detectChangesInternal(this,this._el_61,throwOnChange);
    this._Col_63_3.detectChangesInternal(this,this._el_63,throwOnChange);
    this._List_71_3.detectChangesInternal(this,this._el_71,throwOnChange);
    const currVal_9:any = this.context.itemsPrivacy;
    this._NgFor_73_6.check_ngForOf(currVal_9,throwOnChange,false);
    this._NgFor_73_6.detectChangesInternal(this,this._anchor_73,throwOnChange);
    const currVal_10:any = this.context.items;
    this._NgFor_77_6.check_ngForOf(currVal_10,throwOnChange,false);
    this._NgFor_77_6.detectChangesInternal(this,this._anchor_77,throwOnChange);
    const currVal_12:any = '';
    this._Button_80_4.check_full(currVal_12,throwOnChange,false);
    const currVal_13:any = 'white';
    this._Button_80_4.check_color(currVal_13,throwOnChange,false);
    if (this._Button_80_4.detectChangesInternal(this,this._el_80,throwOnChange)) { this._appEl_80.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'blue';
    this._Typography_81_3.check_color(currVal_14,throwOnChange,false);
    this._Typography_81_3.detectChangesInternal(this,this._el_81,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_7_4.context]);
        this._ToolbarItem_5_3.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_7_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_80_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Content_20_4.context._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'statusbar-padding',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import6.interpolate(1,'',this.context.user.image,'');
    if (import6.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_38,'src',this.viewUtils.sanitizer.sanitize(import47.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import6.interpolate(1,'',this.context.user.name,'');
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_51,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import6.interpolate(1,'',this.context.user.title,'');
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_56,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Slide_24_4.context.ngOnDestroy();
    this._Content_20_4.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onMessage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_80_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AccountLoggedInPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AccountLoggedInPage> {
  if ((renderType_AccountLoggedInPage === (null as any))) { (renderType_AccountLoggedInPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_AccountLoggedInPage,{})); }
  return new _View_AccountLoggedInPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AccountLoggedInPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import48.Wrapper_Item;
  _ItemContent_2_5:import48.Wrapper_ItemContent;
  _query_Label_2_0:import19.QueryList<any>;
  _query_Button_2_1:import19.QueryList<any>;
  _query_Icon_2_2:import19.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountLoggedInPage1,renderType_AccountLoggedInPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'detail-push','');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import48.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import48.Wrapper_Item(this.parent.parentInjector.get(import49.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import50.ItemReorder,(null as any)));
    this._ItemContent_2_5 = new import48.Wrapper_ItemContent();
    this._query_Label_2_0 = new import19.QueryList<any>();
    this._query_Button_2_1 = new import19.QueryList<any>();
    this._query_Icon_2_2 = new import19.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','height: 2px; background-color: #F5F5F5;');
    this._text_6 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import51.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = import6.interpolate(1,'\n          ',this.context.$implicit.note,'\n        ');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemTapped($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AccountLoggedInPage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AccountLoggedInPage1(viewUtils,parentInjector,declarationEl);
}
class _View_AccountLoggedInPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import48.Wrapper_Item;
  _ItemContent_2_5:import48.Wrapper_ItemContent;
  _query_Label_2_0:import19.QueryList<any>;
  _query_Button_2_1:import19.QueryList<any>;
  _query_Icon_2_2:import19.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountLoggedInPage2,renderType_AccountLoggedInPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'detail-push','');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import48.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import48.Wrapper_Item(this.parent.parentInjector.get(import49.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import50.ItemReorder,(null as any)));
    this._ItemContent_2_5 = new import48.Wrapper_ItemContent();
    this._query_Label_2_0 = new import19.QueryList<any>();
    this._query_Button_2_1 = new import19.QueryList<any>();
    this._query_Icon_2_2 = new import19.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','height: 2px; background-color: #F5F5F5;');
    this._text_6 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import51.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = import6.interpolate(1,'\n          ',this.context.$implicit.note,'\n        ');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemTapped($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AccountLoggedInPage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AccountLoggedInPage2(viewUtils,parentInjector,declarationEl);
}